import { formatXof } from "@/lib/format";

/** Taux indicatif USD → XOF pour chiffrer un bon de commande. À recalculer à l’achat. */
export const USD_TO_XOF = 600;

/** Coefficient posé Lomé : fret aérien + assurance + douane + dernier km. */
export const AIR_LANDED = 2.05;

/** Coefficient posé Lomé : groupage mer via le port. */
export const SEA_LANDED = 1.55;

export type BuyPriority = "tête" | "rachat" | "test" | "suivant";
export type FakeRisk = "critique" | "élevé" | "moyen" | "faible";

export type BuyLine = {
  sku: string;
  name: string;
  brand: string;
  format: string;
  inCatalog: boolean;
  catalogSlug?: string;
  priority: BuyPriority;
  fakeRisk: FakeRisk;
  fobUsd: number;
  retailXof: number;
  qtyAir: number;
  qtySea: number;
  moq: number;
  verify: string;
  why: string;
};

export const BUY_WAVE_1: BuyLine[] = [
  {
    sku: "SHB-BJ-RS50",
    name: "Relief Sun Rice + Probiotics SPF50+",
    brand: "Beauty of Joseon",
    format: "50 ml",
    inCatalog: true,
    catalogSlug: "boje-relief-sun",
    priority: "tête",
    fakeRisk: "élevé",
    fobUsd: 11.5,
    retailXof: 15900,
    qtyAir: 24,
    qtySea: 80,
    moq: 12,
    verify: "Hologramme / lot photo + DLC > 14 mois",
    why: "Seul solaire sans white cast du catalogue. Rachat toutes les 6 à 8 semaines. Jamais en rupture.",
  },
  {
    sku: "SHB-CX-GMG",
    name: "Low pH Good Morning Gel Cleanser",
    brand: "COSRX",
    format: "150 ml",
    inCatalog: true,
    catalogSlug: "cosrx-low-ph-cleanser",
    priority: "tête",
    fakeRisk: "moyen",
    fobUsd: 8.8,
    retailXof: 12900,
    qtyAir: 18,
    qtySea: 50,
    moq: 12,
    verify: "QR COSRX Record + pH 5–6 (bandelette)",
    why: "Prix d’entrée < 12 000 F. Premier test de confiance, moins copié que le Snail.",
  },
  {
    sku: "SHB-AN-HL77",
    name: "Heartleaf 77% Soothing Toner",
    brand: "Anua",
    format: "250 ml",
    inCatalog: true,
    catalogSlug: "anua-heartleaf-toner",
    priority: "tête",
    fakeRisk: "moyen",
    fobUsd: 13.2,
    retailXof: 17900,
    qtyAir: 12,
    qtySea: 40,
    moq: 10,
    verify: "Bouchon + batch code Anua, liquide clair verdâtre",
    why: "Meilleur fit climat Lomé (chaleur, rougeurs, pores) — avant le mucin d’escargot.",
  },
  {
    sku: "SHB-CX-SN96",
    name: "Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    format: "100 ml",
    inCatalog: true,
    catalogSlug: "cosrx-snail-96-essence",
    priority: "rachat",
    fakeRisk: "critique",
    fobUsd: 13.5,
    retailXof: 19900,
    qtyAir: 12,
    qtySea: 36,
    moq: 12,
    verify: "QR official.cosrx.com/record — texture filante, incolore, sans parfum",
    why: "Aimant TikTok. Ne jamais brader. Sous 14 USD le flacon source = suspect.",
  },
  {
    sku: "SHB-BJ-GS",
    name: "Glow Serum Propolis + Niacinamide",
    brand: "Beauty of Joseon",
    format: "30 ml",
    inCatalog: true,
    catalogSlug: "boje-glow-serum",
    priority: "rachat",
    fakeRisk: "moyen",
    fobUsd: 12.8,
    retailXof: 18900,
    qtyAir: 8,
    qtySea: 30,
    moq: 8,
    verify: "Lot BOJ + consistance miel fluide",
    why: "Soin taches / éclat, associé au SPF. Allergie propolis à rappeler.",
  },
  {
    sku: "SHB-BJ-RB",
    name: "Red Bean Water Gel",
    brand: "Beauty of Joseon",
    format: "100 ml",
    inCatalog: true,
    catalogSlug: "boje-red-bean-gel",
    priority: "rachat",
    fakeRisk: "faible",
    fobUsd: 11.2,
    retailXof: 18500,
    qtyAir: 8,
    qtySea: 24,
    moq: 8,
    verify: "Lot BOJ, gel frais non collant",
    why: "Hydratant saison des pluies. Léger sous le Relief Sun.",
  },
  {
    sku: "SHB-MD-ZP2",
    name: "Zero Pore Pad 2.0",
    brand: "Medicube",
    format: "70 pads",
    inCatalog: true,
    catalogSlug: "medicube-zero-pore-pad",
    priority: "test",
    fakeRisk: "élevé",
    fobUsd: 16.5,
    retailXof: 23900,
    qtyAir: 6,
    qtySea: 20,
    moq: 6,
    verify: "Uniquement circuit APR / Medicube — pas de PDRN gris",
    why: "Avant/après TikTok. Lots hors circuit officiel déjà rappelés (colorants).",
  },
  {
    sku: "SHB-AR-RM",
    name: "Rice Mucin Face Cleanser",
    brand: "Arencia",
    format: "120 g",
    inCatalog: true,
    catalogSlug: "arencia-rice-mochi",
    priority: "test",
    fakeRisk: "faible",
    fobUsd: 14,
    retailXof: 20900,
    qtyAir: 6,
    qtySea: 18,
    moq: 6,
    verify: "Pot d’origine, texture mochi",
    why: "Produit découverte, moins copié. Bon récit « riz » pour le teint.",
  },
  {
    sku: "SHB-MD-CNM",
    name: "Collagen Night Wrapping Mask",
    brand: "Medicube",
    format: "75 ml",
    inCatalog: true,
    catalogSlug: "medicube-collagen-mask",
    priority: "test",
    fakeRisk: "élevé",
    fobUsd: 17.5,
    retailXof: 26500,
    qtyAir: 6,
    qtySea: 16,
    moq: 6,
    verify: "Distributeur APR, DLC, film wrapping intact",
    why: "Cadeau / ticket haut. Volumes serrés : DLC et fakes PDRN.",
  },
];

export const BUY_WAVE_2: BuyLine[] = [
  {
    sku: "SHB-S1-CA55",
    name: "Madagascar Centella Ampoule",
    brand: "SKIN1004",
    format: "55 ml",
    inCatalog: true,
    catalogSlug: "skin1004-centella-ampoule",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 8.5,
    retailXof: 12900,
    qtyAir: 10,
    qtySea: 30,
    moq: 10,
    verify: "Dropper SKIN1004, liquide centella clair",
    why: "Calme acné + chaleur. Déjà un réflexe en Afrique, moins fake que COSRX.",
  },
  {
    sku: "SHB-AN-PCO",
    name: "Heartleaf Pore Control Cleansing Oil",
    brand: "Anua",
    format: "200 ml",
    inCatalog: true,
    catalogSlug: "anua-pore-cleansing-oil",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 14,
    retailXof: 20500,
    qtyAir: 8,
    qtySea: 24,
    moq: 8,
    verify: "Pompe Anua, huile qui s’émulsionne au contact de l’eau",
    why: "Premier nettoyage (SPF + pollution Lomé). Complète le Low pH.",
  },
  {
    sku: "SHB-RL-BJ50",
    name: "Birch Juice Moisturizing Sunscreen SPF50+",
    brand: "Round Lab",
    format: "50 ml",
    inCatalog: true,
    catalogSlug: "round-lab-birch-sun",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 12,
    retailXof: 15900,
    qtyAir: 12,
    qtySea: 40,
    moq: 10,
    verify: "Tube Round Lab, fini fluide, pas de film blanc",
    why: "Plan B solaire si rupture Relief Sun. Peaux mixtes/grasses.",
  },
  {
    sku: "SHB-CX-S92",
    name: "Advanced Snail 92 All in One Cream",
    brand: "COSRX",
    format: "100 g",
    inCatalog: true,
    catalogSlug: "cosrx-snail-92-cream",
    priority: "suivant",
    fakeRisk: "critique",
    fobUsd: 13,
    retailXof: 18900,
    qtyAir: 8,
    qtySea: 24,
    moq: 8,
    verify: "QR COSRX Record — jamais sous 12 USD FOB",
    why: "Upsell du Snail 96. Même exigence anti-faux.",
  },
  {
    sku: "SHB-AN-TXA",
    name: "Niacinamide 10% + TXA 4% Serum",
    brand: "Anua",
    format: "30 ml",
    inCatalog: true,
    catalogSlug: "anua-txa-serum",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 13.8,
    retailXof: 20500,
    qtyAir: 8,
    qtySea: 24,
    moq: 8,
    verify: "Flacon Anua, sérum fluide",
    why: "Taches / PIH sans hydroquinone — le besoin n°1 en pharmacie à Lomé.",
  },
  {
    sku: "SHB-DA-WTFS",
    name: "White Truffle First Spray Serum",
    brand: "d'Alba",
    format: "100 ml",
    inCatalog: true,
    catalogSlug: "dalba-first-spray",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 16.5,
    retailXof: 24900,
    qtyAir: 8,
    qtySea: 24,
    moq: 6,
    verify: "Spray or d'Alba, couches eau/huile visibles après agitation",
    why: "Best-seller UMMA. Cadeau / éclat TikTok. Agiter avant chaque use.",
  },
  {
    sku: "SHB-AN-P70",
    name: "Peach 70 Niacin Serum",
    brand: "Anua",
    format: "30 ml",
    inCatalog: true,
    catalogSlug: "anua-peach-70-serum",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 12.5,
    retailXof: 18900,
    qtyAir: 8,
    qtySea: 20,
    moq: 8,
    verify: "Flacon Anua 70+ rose",
    why: "Éclat quotidien, moins agressif que le TXA. Rachat facile.",
  },
  {
    sku: "SHB-S1-HCS",
    name: "Hyalu-Cica Water-Fit Sun Serum SPF50+",
    brand: "SKIN1004",
    format: "50 ml",
    inCatalog: true,
    catalogSlug: "skin1004-hyalu-cica-sun",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 12.2,
    retailXof: 16900,
    qtyAir: 12,
    qtySea: 40,
    moq: 10,
    verify: "Tube SKIN1004, fini fluide, swatch white-cast sur peau foncée",
    why: "Second solaire tête de gondole. Texture eau, chaleur de Lomé.",
  },
  {
    sku: "SHB-BJ-GDS",
    name: "Glow Deep Serum Rice + Alpha-Arbutin",
    brand: "Beauty of Joseon",
    format: "30 ml",
    inCatalog: true,
    catalogSlug: "boje-glow-deep",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 12,
    retailXof: 17900,
    qtyAir: 8,
    qtySea: 24,
    moq: 8,
    verify: "Compte-gouttes BOJ, sérum ambré",
    why: "Taches / PIH, complète le Glow Serum propolis. Toujours + SPF.",
  },
  {
    sku: "SHB-GD-VTC",
    name: "Green Tangerine Vita C Dark Spot Serum",
    brand: "Goodal",
    format: "40 ml",
    inCatalog: true,
    catalogSlug: "goodal-vita-c",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 13.5,
    retailXof: 19900,
    qtyAir: 8,
    qtySea: 20,
    moq: 6,
    verify: "Flacon Goodal jaune, pompe verte, DLC ≥ 14 mois (vit C)",
    why: "Viral taches UMMA. Conserver au frais, pas en vitrine soleil.",
  },
  {
    sku: "SHB-NB-N5",
    name: "No.5 Glutathione Vitamin Concentrated Serum",
    brand: "numbuzin",
    format: "30 ml",
    inCatalog: true,
    catalogSlug: "numbuzin-no5",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 15,
    retailXof: 21900,
    qtyAir: 6,
    qtySea: 18,
    moq: 6,
    verify: "Flacon noir numbuzin 5+, hologramme lot",
    why: "Sérum taches premium (glutathion + TXA + vit C). Ticket plus haut.",
  },
  {
    sku: "SHB-TD-DI50",
    name: "DIVE-IN Low Molecular Hyaluronic Acid Serum",
    brand: "Torriden",
    format: "50 ml",
    inCatalog: true,
    catalogSlug: "torriden-dive-in",
    priority: "suivant",
    fakeRisk: "faible",
    fobUsd: 11.5,
    retailXof: 17500,
    qtyAir: 8,
    qtySea: 24,
    moq: 8,
    verify: "Flacon Torriden bleu, pipette blanche",
    why: "Hydratation clim / harmattan. Peu copié, rachat facile.",
  },
  {
    sku: "SHB-CX-BHA",
    name: "BHA Blackhead Power Liquid",
    brand: "COSRX",
    format: "100 ml",
    inCatalog: true,
    catalogSlug: "cosrx-bha-liquid",
    priority: "suivant",
    fakeRisk: "élevé",
    fobUsd: 11.8,
    retailXof: 16900,
    qtyAir: 8,
    qtySea: 24,
    moq: 8,
    verify: "QR COSRX Record + liquide incolore",
    why: "Points noirs, complète le Low pH. Jamais sans facture coréenne.",
  },
  {
    sku: "SHB-BD-BCM",
    name: "Bio-Collagen Real Deep Mask",
    brand: "Biodance",
    format: "4 masques",
    inCatalog: true,
    catalogSlug: "biodance-collagen-mask",
    priority: "suivant",
    fakeRisk: "moyen",
    fobUsd: 13,
    retailXof: 19500,
    qtyAir: 8,
    qtySea: 20,
    moq: 6,
    verify: "Boîte Biodance rose, 4 sachets scellés, DLC",
    why: "Masque viral UMMA. Cadeau / ticket soirée, DLC courte à surveiller.",
  },
  {
    sku: "SHB-RM-JLT32",
    name: "Juicy Lasting Tint — Bare Grape",
    brand: "rom&nd",
    format: "5,5 g",
    inCatalog: true,
    catalogSlug: "romand-juicy-tint",
    priority: "suivant",
    fakeRisk: "faible",
    fobUsd: 6.5,
    retailXof: 9600,
    qtyAir: 12,
    qtySea: 36,
    moq: 12,
    verify: "Tube rom&nd dégradé, teinte Bare Grape",
    why: "Entrée maquillage. Teinte portable peaux mates, tenue chaleur.",
  },
  {
    sku: "SHB-LN-LSM20",
    name: "Lip Sleeping Mask Berry",
    brand: "Laneige",
    format: "20 g",
    inCatalog: true,
    catalogSlug: "laneige-lip-sleeping-mask",
    priority: "tête",
    fakeRisk: "élevé",
    fobUsd: 9.5,
    retailXof: 15900,
    qtyAir: 18,
    qtySea: 48,
    moq: 12,
    verify: "Pot rose Laneige Berry 20 g + spatule, lot Amorepacific",
    why: "Best-seller UMMA La Neige. Rachat lèvres, cadeau, ticket < 16 000 F.",
  },
  {
    sku: "SHB-LN-LGB10",
    name: "Lip Glowy Balm Berry",
    brand: "Laneige",
    format: "10 g",
    inCatalog: true,
    catalogSlug: "laneige-lip-glowy-balm",
    priority: "tête",
    fakeRisk: "moyen",
    fobUsd: 6.8,
    retailXof: 9900,
    qtyAir: 18,
    qtySea: 48,
    moq: 12,
    verify: "Tube Laneige Lip Glowy Balm Berry 10 g",
    why: "Relais jour du Lip Sleeping Mask. Entrée maquillage.",
  },
  {
    sku: "SHB-LN-WSM70",
    name: "Water Sleeping Mask",
    brand: "Laneige",
    format: "70 ml",
    inCatalog: true,
    catalogSlug: "laneige-water-sleeping-mask",
    priority: "rachat",
    fakeRisk: "élevé",
    fobUsd: 16,
    retailXof: 26900,
    qtyAir: 10,
    qtySea: 24,
    moq: 8,
    verify: "Pot bleu Laneige Water Sleeping Mask 70 ml",
    why: "Masque nuit hydratation. Viral UMMA, climat chaud.",
  },
  {
    sku: "SHB-TT-MFRC40",
    name: "Mask Fit Red Cushion — 40N Cinnamon",
    brand: "TIRTIR",
    format: "18 g",
    inCatalog: true,
    catalogSlug: "tirtir-mask-fit-40n",
    priority: "tête",
    fakeRisk: "élevé",
    fobUsd: 18,
    retailXof: 26900,
    qtyAir: 8,
    qtySea: 20,
    moq: 6,
    verify: "Boîtier rouge TIRTIR 40N Cinnamon scellé",
    why: "Teinte profonde pour Lomé. Complète le 33N.",
  },
];

export const SOURCES = [
  {
    name: "UMMA (Craver)",
    kind: "Grossiste K-beauty Corée",
    url: "https://umma.io",
    moq: "MOA 500 USD 1re commande · U-Quick dès 5 pcs",
    when: "Réassort vague 1 et 2. Prix FOB, lots, COA. Compte pro obligatoire.",
    caution: "Vérifier U-Quick vs standard. Ne jamais mixer un carton gris « Dubai ».",
  },
  {
    name: "Olive Young Global",
    kind: "Boutique officielle Corée",
    url: "https://global.oliveyoung.com",
    moq: "1 pièce — idéal test",
    when: "Commande aérienne de validation, DLC longue, facture claire.",
    caution: "Prix quasi retail. Ne pas s’en servir pour le stock mer.",
  },
  {
    name: "StyleKorean / YesStyle (compte pro)",
    kind: "Grossiste K-beauty",
    url: "https://www.stylekorean.com",
    moq: "Souvent 6–12 / SKU",
    when: "Réassort vague 1 une fois les 9 SKU validés.",
    caution: "Vérifier « authorized » COSRX / Anua / BOJ, pas le marketplace tiers.",
  },
  {
    name: "COSRX Official / Jolse",
    kind: "Marque",
    url: "https://www.cosrx.com",
    moq: "Carton export",
    when: "Dès que le Snail tourne. Seul circuit pour le QR Record.",
    caution: "Refuser tout COSRX sans invoice coréenne + QR.",
  },
  {
    name: "APR (Medicube)",
    kind: "Marque",
    url: "https://medicube.co.kr",
    moq: "Selon distributeur Afrique / Europe",
    when: "Pads et masques uniquement. Pas de devices au lancement.",
    caution: "Lots PDRN hors circuit déjà saisis (colorant interdit). Zéro gris.",
  },
  {
    name: "À écarter",
    kind: "Risque",
    url: "",
    moq: "—",
    when: "Jamais.",
    caution:
      "AliExpress, 1688 anonyme, carton « Dubai », Instagram « direct Corée » sans facture, Ubuy pour du stock (lent, cher, pas de maîtrise de lot).",
  },
] as const;

export const RECEIVING_CHECKS = [
  "Facture fournisseur + packing list + n° de lot par SKU, archivés.",
  "Photo de chaque carton à l’ouverture (scellé, code pays 82 si départ Corée).",
  "Scanner le QR COSRX Record sur 100 % des Snail 96 et Snail 92.",
  "DLC restante ≥ 14 mois — sinon mettre en promo interne, pas en tête de gondole.",
  "Texture Snail : filante, transparente, inodore. Trouble / parfum = quarantaine.",
  "Relief Sun : swatch sur peau foncée, zéro film blanc. Sinon lot suspect.",
  "Prix d’achat FOB Snail 96 ≥ 14 USD. En dessous : ne pas mettre en ligne.",
  "Saisir lot + DLC sur la fiche produit avant de passer le stock à « actif ».",
] as const;

export function landedXof(fobUsd: number, mode: "air" | "sea"): number {
  const mult = mode === "air" ? AIR_LANDED : SEA_LANDED;
  return Math.round(fobUsd * USD_TO_XOF * mult);
}

export function lineTotal(line: BuyLine, mode: "air" | "sea"): number {
  const qty = mode === "air" ? line.qtyAir : line.qtySea;
  return landedXof(line.fobUsd, mode) * qty;
}

export function waveTotals(lines: BuyLine[], mode: "air" | "sea") {
  const units = lines.reduce((n, l) => n + (mode === "air" ? l.qtyAir : l.qtySea), 0);
  const fobUsd = lines.reduce(
    (n, l) => n + l.fobUsd * (mode === "air" ? l.qtyAir : l.qtySea),
    0,
  );
  const landed = lines.reduce((n, l) => n + lineTotal(l, mode), 0);
  const retail = lines.reduce(
    (n, l) => n + l.retailXof * (mode === "air" ? l.qtyAir : l.qtySea),
    0,
  );
  return { units, fobUsd, landed, retail };
}

export function purchaseOrderText(mode: "air" | "sea"): string {
  const lines = BUY_WAVE_1;
  const t = waveTotals(lines, mode);
  const title = mode === "air" ? "COMMANDE TEST AÉRIENNE" : "COMMANDE MER — RÉASSORT";
  const body = lines
    .map((l) => {
      const qty = mode === "air" ? l.qtyAir : l.qtySea;
      return `- ${l.sku}  ${l.brand} · ${l.name} (${l.format})  × ${qty}  FOB ${l.fobUsd.toFixed(2)} USD`;
    })
    .join("\n");
  return [
    `Skinhealthb — ${title}`,
    `Taux indicatif ${USD_TO_XOF} F CFA / USD`,
    "",
    body,
    "",
    `Unités : ${t.units}`,
    `FOB : ${t.fobUsd.toFixed(0)} USD`,
    `Coût posé Lomé estimé : ${formatXof(t.landed)}`,
    `Valeur vente catalogue : ${formatXof(t.retail)}`,
    "",
    "Conditions : facture coréenne, lots, DLC ≥ 14 mois, QR COSRX Record sur Snail.",
    "Ne pas acheter de COSRX Snail 96 sous 14 USD FOB.",
  ].join("\n");
}

export const PRIORITY_LABEL: Record<BuyPriority, string> = {
  tête: "Tête de gondole",
  rachat: "Rachat",
  test: "Test",
  suivant: "Vague 2",
};

export const RISK_LABEL: Record<FakeRisk, string> = {
  critique: "Faux : critique",
  élevé: "Faux : élevé",
  moyen: "Faux : moyen",
  faible: "Faux : faible",
};
