-- Rayon dm (2e vague) : e.l.f., INAO, nerds., Acnemy Zitcalm, Nø, L'Oréal,
-- Geek & Gorgeous, hautsache, Garnier, Neutrogena, Balea MED, Dejan Garz, Herbal.
-- Prix = tarif dm.de × 656 XOF, arrondi 50 F.

insert into brands (id, slug, name, country, verified) values
  (36, 'elf', 'e.l.f. Skin', 'États-Unis', true),
  (37, 'inao', 'INAO', 'Allemagne', true),
  (38, 'nerds', 'nerds.', 'Hongrie', true),
  (39, 'no-cosmetics', 'Nø Cosmetics', 'Allemagne', true),
  (40, 'loreal', 'L''Oréal Paris', 'France', true),
  (41, 'geek-gorgeous', 'Geek & Gorgeous', 'Hongrie', true),
  (42, 'hautsache', 'hautsache', 'Allemagne', true),
  (43, 'herbal-essences', 'Herbal Essences', 'États-Unis', true),
  (44, 'dejan-garz', 'Dejan Garz', 'Allemagne', true)
on conflict (slug) do nothing;

-- Zitcontrol du rayon = version SPF 50 (boîte photographiée).
update products set
  name = 'Crème Zitcontrol SPF 50',
  description = $d$Crème Acnemy Zitcontrol SPF 50, 40 ml. Hydrate, aide à contrôler les imperfections et protège (SPF 50, UVA/UVB). Acide salicylique, niacinamide, zinc PCA. Non comédogène, fini sec. Tarif dm.de 18,95 €.$d$,
  ingredients = $d$Aqua, UV filters, niacinamide, salicylic acid, zinc PCA, glycerin. Oil-free. Liste complète sur l'emballage.$d$,
  usage_tips = $d$Dernière étape du matin : une noisette sur visage et cou. Renouveler toutes les 2 h en plein soleil.$d$,
  precautions = $d$Usage externe. Éviter les yeux. Ceci n'est pas un médicament. La protection solaire ne remplace pas l'ombre.$d$,
  format_label = '40 ml SPF 50',
  image_url = '/products/acnemy-zitcontrol-spf.jpg?v=13',
  is_new = true,
  is_active = true
where slug = 'acnemy-zitcontrol';

insert into products (
  id, slug, name, brand_id, category_id, description, ingredients, usage_tips, precautions,
  format_label, origin, authenticity_note, price_xof, compare_at_xof, stock, sku, image_url,
  skin_types, hair_types, is_featured, is_new, is_bestseller, is_active, lot_number, expires_on
) values

(82, 'elf-thirst-toner', 'Toner Thirst Burst Pore-fecting', 36, 1,
 $d$Toner e.l.f. Skin Thirst Burst 140 ml. 2 % BHA (acide salicylique) pour désincruster les pores + 1 % complexe hibiscus pour hydrater sans tirer. Fini frais, vegan. Tarif dm.de 13,95 €.$d$,
 $d$Aqua, salicylic acid 2 %, hibiscus complex 1 %, glycerin. Liste complète sur l'emballage.$d$,
 $d$Après le nettoyage, tamponner avec les mains ou un coton. Matin et/ou soir. Suivre d'un sérum.$d$,
 $d$Usage externe. Éviter les yeux. Peut piquer sur peau lésée (BHA). Patch-test 24 h.$d$,
 '140 ml', 'États-Unis', 'Boîte e.l.f. Skin rose d''origine, import dm Allemagne.',
 9150, null, 20, 'SHB-EL-TB140', '/products/elf-thirst-toner.jpg?v=13',
 'grasse,mixte,acneique,normale', null, true, true, true, true, 'E26-301', '2028-06-30'),

(83, 'elf-thirst-drops', 'Drops Thirst Burst Holy Hydration', 36, 1,
 $d$Sérum-gel e.l.f. Skin Thirst Burst Drops 30 ml. 5 % niacinamide, acide hyaluronique et complexe hibiscus : glow immédiat, pores plus nets, teint plus rebondi. Se mélange à la crème ou au fond de teint. Tarif dm.de 14,95 €.$d$,
 $d$Aqua, niacinamide 5 %, sodium hyaluronate, hibiscus complex 1 %. Liste complète sur l'emballage.$d$,
 $d$2 à 3 pompes sur peau propre, seul, sous la crème, ou mixé au teint.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '30 ml', 'États-Unis', 'Flacon pompe e.l.f. Skin bleu d''origine, scellé.',
 9800, null, 18, 'SHB-EL-TD30', '/products/elf-thirst-drops.jpg?v=13',
 'normale,mixte,sèche,terne', null, true, true, true, true, 'E26-302', '2028-06-30'),

(84, 'inao-feel-pure', 'Gel nettoyant Feel Pure', 37, 1,
 $d$Gel INAO Feel Pure 175 ml (by essence). 1 % AHA + 2 % BHA : exfolie en nettoyant, lisse le grain, sans savon. Vegan. Tarif dm.de 7,95 €.$d$,
 $d$Aqua, AHA 1 %, BHA 2 %, mild surfactants, niacinamide. Liste complète sur le flacon.$d$,
 $d$Soir, masser 30 secondes sur visage mouillé, rincer. 2 à 3 fois par semaine si peau sensible.$d$,
 $d$Usage externe. Éviter les yeux. Ne pas superposer d'autres acides le même soir au début.$d$,
 '175 ml', 'Allemagne', 'Flacon pompe INAO dégradé vert-jaune d''origine essence / dm.',
 5200, null, 24, 'SHB-IN-FP175', '/products/inao-feel-pure.jpg?v=13',
 'grasse,mixte,acneique,normale', null, true, true, true, true, 'I26-110', '2028-07-31'),

(85, 'inao-fine-time', 'Brume Fine Time Daily Hypo', 37, 1,
 $d$Brume INAO Fine Time Daily Hypo 100 ml. Spray visage à l'acide hypochloreux : apaise, assainit, convient aux peaux à boutons. Usage tout au long de la journée. Tarif dm.de 7,95 €.$d$,
 $d$Aqua, hypochlorous acid, soothing agents. Liste complète sur le flacon.$d$,
 $d$Vaporiser à 15 cm sur visage propre, matin, soir ou sur boutons en journée. Laisser sécher.$d$,
 $d$Usage externe. Éviter les yeux. Tenir hors de portée des enfants.$d$,
 '100 ml', 'Allemagne', 'Spray INAO violet d''origine, lot photographié en rayon dm.',
 5200, null, 22, 'SHB-IN-FT100', '/products/inao-fine-time.jpg?v=13',
 'acneique,mixte,sensible,grasse', null, false, true, false, true, 'I26-111', '2028-07-31'),

(86, 'inao-clean-crush', 'Eau micellaire Clean Crush', 37, 1,
 $d$Eau micellaire INAO Clean Crush 500 ml. Mizelles + 5 % glycérine + centella : démaquille sans frotter, hydrate. Grand format, vegan. Tarif dm.de 4,45 €.$d$,
 $d$Aqua, glycerin 5 %, PEG-6 caprylic/capric glycerides, centella asiatica leaf extract. Liste complète sur le flacon.$d$,
 $d$Imbiber un coton, passer sur visage et yeux. Pas besoin de rincer. Convient au démaquillage du soir.$d$,
 $d$Usage externe. Éviter de verser dans les yeux.$d$,
 '500 ml', 'Allemagne', 'Grand flacon INAO bleu d''origine, 500 ml, import dm.',
 2900, null, 30, 'SHB-IN-CC500', '/products/inao-clean-crush.jpg?v=13',
 'tous,sensible,normale,mixte', null, false, true, true, true, 'I26-112', '2028-08-31'),

(87, 'inao-hydra-soul', 'Gel-crème Hydra Soul 24h', 37, 1,
 $d$Gel-crème INAO Hydra Soul 24h, 50 ml. 5 % niacinamide, céramides, bakuchiol et karité : hydrate 24 h, lisse, éclat. Texture gel, vegan, non grasse. Tarif dm.de 9,95 €.$d$,
 $d$Aqua, glycerin, niacinamide 5 %, ceramides, bakuchiol, shea butter, aloe. Liste complète sur le pot.$d$,
 $d$Matin et soir, une noisette sur visage et cou après le sérum. Le jour : terminer par un SPF.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '50 ml', 'Allemagne', 'Pot INAO Hydra Soul d''origine, scellé.',
 6550, null, 20, 'SHB-IN-HS50', '/products/inao-hydra-soul.jpg?v=13',
 'normale,mixte,sèche,terne', null, false, true, true, true, 'I26-113', '2028-07-31'),

(88, 'nerds-azelaic', 'Sérum 10 % acide azélaïque', 38, 1,
 $d$Crème-sérum nerds. 10 % Azelaic Acid 30 ml. 10 % acide azélaïque + 3 % niacinamide : boutons, rougeurs, taches, pores. Texture légère, vegan, sans parfum. Tarif dm.de 13,85 €.$d$,
 $d$Aqua, azelaic acid 10 %, niacinamide 3 %, squalane, bisabolol, allantoin, tocopherol. Liste complète sur l'emballage.$d$,
 $d$Soir, une pompe sur peau propre. Introduire 1 soir sur 2 si peau sensible. Le jour : SPF obligatoire.$d$,
 $d$Usage externe. Éviter les yeux. Peut piquer en début de routine. Ceci n'est pas un médicament.$d$,
 '30 ml', 'Hongrie', 'Flacon nerds. d''origine, import dm exclusif.',
 9100, null, 18, 'SHB-ND-AZ30', '/products/nerds-azelaic.jpg?v=13',
 'acneique,mixte,grasse,taches,sensible', null, true, true, true, true, 'N26-401', '2028-05-31'),

(89, 'nerds-peptide', 'Crème Multi-Peptide Smart-Aging', 38, 1,
 $d$Crème nerds. Multi-Peptide Smart-Aging 50 ml. 2 % Argireline Amplified + 3 % Syn-Coll : lisse les ridules, raffermit. Squalane, hyaluron, karité. Vegan, sans parfum. Tarif dm.de 20,85 €.$d$,
 $d$Aqua, palmitoyl tripeptide-5, acetyl hexapeptide-8, squalane, sodium hyaluronate, shea butter, panthenol. Liste complète sur l'emballage.$d$,
 $d$Matin et/ou soir, une noisette sur visage et cou. Seul ou après un sérum.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '50 ml', 'Hongrie', 'Flacon pompe nerds. d''origine, scellé, import dm.',
 13700, null, 14, 'SHB-ND-MP50', '/products/nerds-peptide.jpg?v=13',
 'normale,sèche,mature,mixte', null, true, true, false, true, 'N26-402', '2028-05-31'),

(90, 'acnemy-zitcalm-serum', 'Sérum Zitcalm anti-rougeurs', 34, 1,
 $d$Sérum Acnemy Zitcalm 30 ml. Calme les rougeurs après un traitement anti-acné (beta-glucane, réglisse). Oil-free, vegan, sans parfum. Tarif dm.de 14,95 €.$d$,
 $d$Aqua, beta-glucan, glycyrrhiza glabra root extract, panthenol. Sans huile. Liste complète sur l'emballage.$d$,
 $d$Soir, 3 à 4 gouttes sur zones rouges, après le nettoyage. Peut suivre Postzit.$d$,
 $d$Usage externe. Patch-test 24 h. Ceci n'est pas un médicament.$d$,
 '30 ml', 'Espagne', 'Boîte Acnemy Zitcalm Serum d''origine, import dm.',
 9800, null, 16, 'SHB-AC-ZS30', '/products/acnemy-zitcalm-serum.jpg?v=13',
 'acneique,sensible,mixte,rougeurs', null, true, true, true, true, 'A26-044', '2028-04-30'),

(91, 'acnemy-zitcalm-creme', 'Crème Zitcalm apaisante', 34, 1,
 $d$Crème Acnemy Zitcalm 50 ml. Répare la barrière après un traitement desséchant : vitamine F, bisabolol, allantoïne. Légère, non comédogène. Tarif dm.de 14,95 €.$d$,
 $d$Aqua, vitamin F, bisabolol, allantoin, glycerin. Non comédogène. Liste complète sur l'emballage.$d$,
 $d$Matin et/ou soir, une noisette sur visage. Le jour : Zitcontrol SPF par-dessus.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '50 ml', 'Espagne', 'Boîte Acnemy Zitcalm Moisturizer d''origine, import dm.',
 9800, null, 16, 'SHB-AC-ZC50', '/products/acnemy-zitcalm-creme.jpg?v=13',
 'acneique,sensible,sèche,mixte', null, false, true, false, true, 'A26-045', '2028-04-30'),

(92, 'no-daily-mist', 'Brume Daily Skin Guard', 39, 1,
 $d$Brume Nø Cosmetics Daily Skin Guard 120 ml. 0,02 % acide hypochloreux, pH neutre : apaise rougeurs et boutons, visage et corps. 2 ingrédients. Tarif dm.de 12,95 €.$d$,
 $d$Aqua (water), hypochlorous acid.$d$,
 $d$Vaporiser à tout moment sur peau propre, y compris sur le corps. Laisser sécher. Idéal après le sport ou sous le masque.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '120 ml', 'Allemagne', 'Spray Nø rose Daily Skin Guard d''origine, import dm.',
 8500, null, 18, 'SHB-NO-DS120', '/products/no-daily-mist.jpg?v=13',
 'acneique,sensible,mixte,rougeurs', null, false, true, false, true, 'O26-201', '2028-06-30'),

(93, 'no-hypercalm', 'Sérum HyperCalm 2-phases', 39, 1,
 $d$Sérum Nø HyperCalm 2-phases 20 ml. 5 % acide azélaïque + indirubine (pastel) + céramides : boutons, points noirs, rougeurs. À secouer. Tarif dm.de 15,95 €.$d$,
 $d$Aqua, azelaic acid 5 %, indirubin, ceramides, apricot oil, avocado oil, tomato extract. Liste complète sur le flacon.$d$,
 $d$Secouer, 3 pompes le soir sur peau propre. 28 jours d'usage régulier.$d$,
 $d$Usage externe. Éviter les yeux. Ceci n'est pas un médicament.$d$,
 '20 ml', 'Allemagne', 'Sérum Nø HyperCalm d''origine, flacon rose, scellé.',
 10450, null, 14, 'SHB-NO-HC20', '/products/no-hypercalm.jpg?v=13',
 'acneique,mixte,grasse,rougeurs', null, false, true, false, true, 'O26-202', '2028-05-31'),

(94, 'no-calming', 'Crème hydratante apaisante', 39, 1,
 $d$Crème Nø Cosmetics apaisante 50 ml. Formule Pink Power (indirubine), céramides, panthénol, extrait de tomate : barrière, rougeurs, confort. Sans parfum. Tarif dm.de 15,95 €.$d$,
 $d$Aqua, ceramides, panthenol, indirubin, tomato extract. Sans parfum, vegan. Liste complète sur l'emballage.$d$,
 $d$Matin et soir, une noisette après le sérum. Tous types, y compris sensibles.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '50 ml', 'Allemagne', 'Boîte Nø crème apaisante d''origine, import dm.',
 10450, null, 14, 'SHB-NO-CA50', '/products/no-calming.jpg?v=13',
 'sensible,normale,sèche,rougeurs', null, false, true, false, true, 'O26-203', '2028-05-31'),

(95, 'no-hypershield', 'Crème HyperShield LSF 30', 39, 1,
 $d$Crème Nø HyperShield LSF 30, 50 ml. Filtres hybrides UVA/UVB, vitamine E, thé vert, échinacée : solaire quotidien + antioxydants. Sans parfum. Tarif dm.de 14,95 €.$d$,
 $d$Aqua, UV filters, glycerin, shea butter, tocopherol, green tea, echinacea, squalane. Liste complète sur l'emballage.$d$,
 $d$Dernière étape du matin : une noisette généreuse. Renouveler en exposition.$d$,
 $d$Usage externe. La protection solaire ne remplace pas l'ombre ni le chapeau.$d$,
 '50 ml LSF 30', 'Allemagne', 'Boîte Nø HyperShield d''origine, import dm.',
 9800, null, 16, 'SHB-NO-HS50', '/products/no-hypershield.jpg?v=13',
 'tous,sensible,normale,mixte', null, true, true, true, true, 'O26-204', '2028-04-30'),

(96, 'gg-power-peptides', 'Sérum 101 Power Peptides', 41, 1,
 $d$Sérum Geek & Gorgeous 101 Power Peptides 30 ml. Quatre peptides (pro-collagène) : fermeté, ridules, élasticité. Texture laiteuse, vegan, sans parfum. Tarif dm.de 15,35 €.$d$,
 $d$Aqua, multi-peptide complex, glycerin. Sans parfum. Liste complète sur le flacon.$d$,
 $d$Matin et/ou soir, 3 à 4 gouttes sur visage et cou, avant la crème.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '30 ml', 'Hongrie', 'Flacon pipette Geek & Gorgeous 101 d''origine, import dm.',
 10050, null, 16, 'SHB-GG-PP30', '/products/gg-power-peptides.jpg?v=13',
 'normale,sèche,mature,mixte', null, true, true, false, true, 'G26-501', '2028-06-30'),

(97, 'gg-ha5', 'Sérum 101 HA 5 Rich', 41, 1,
 $d$Sérum Geek & Gorgeous 101 HA 5 Rich 30 ml. Cinq poids d'acide hyaluronique + panthénol : peau déshydratée, rebond, soie. Vegan. Tarif dm.de 9,35 €.$d$,
 $d$Aqua, sodium hyaluronate, hyaluronic acid, tremella, panthenol, betaine, glycerin. Liste complète sur le flacon.$d$,
 $d$Matin et soir, 3 gouttes sur peau encore humide, avant la crème.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '30 ml', 'Hongrie', 'Flacon Geek & Gorgeous HA 5 Rich d''origine.',
 6150, null, 20, 'SHB-GG-HA30', '/products/gg-ha5.jpg?v=13',
 'sèche,déshydratée,normale,mixte', null, false, true, true, true, 'G26-502', '2028-06-30'),

(98, 'hautsache-barriere', 'Sérum Barrière céramides', 42, 1,
 $d$Sérum hautsache Barrière 30 ml (dm × fraubeauty). 1 % complexe céramides + 0,3 % ectoine : renforce la barrière, protège du climat. Vegan, sans parfum. Tarif dm.de 7,95 €.$d$,
 $d$Aqua, ceramide complex 1 %, ectoin 0,3 %, glycerin. Sans parfum. Liste complète sur l'emballage.$d$,
 $d$Matin et soir, quelques gouttes avant la crème. Idéal harmattan / clim.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '30 ml', 'Allemagne', 'Boîte hautsache Barriere Serum d''origine dm.',
 5200, null, 22, 'SHB-HS-BR30', '/products/hautsache-barriere.jpg?v=13',
 'sensible,sèche,normale,barrière', null, false, true, false, true, 'H26-301', '2028-08-31'),

(99, 'loreal-laser', 'Crème Revitalift Laser nuit', 40, 1,
 $d$Crème L'Oréal Paris Revitalift Laser X3 nuit 50 ml. Pro-rétinol, acide hyaluronique, vitamine C : ridules, fermeté, éclat. Tarif dm.de 16,95–17,95 €.$d$,
 $d$Aqua, pro-retinol, hyaluronic acid, vitamin C, glycerin. Liste complète sur le pot.$d$,
 $d$Soir, une noisette sur visage et cou, après le sérum. Le matin : SPF.$d$,
 $d$Usage externe. Contient un dérivé de rétinol : éviter grossesse sans avis. Peut dessécher au début.$d$,
 '50 ml', 'France', 'Pot L''Oréal Revitalift Laser d''origine, scellé, import dm.',
 11100, null, 12, 'SHB-LO-RL50', '/products/loreal-laser.jpg?v=13',
 'mature,normale,sèche,mixte', null, false, true, false, true, 'L26-701', '2028-03-31'),

(100, 'loreal-filler', 'Crème Revitalift Filler', 40, 1,
 $d$Crème L'Oréal Paris Revitalift Filler 50 ml. Acide hyaluronique : effet volume, ridules, hydratation. Texture confort. Tarif rayon dm ~12,95 €.$d$,
 $d$Aqua, hyaluronic acid, glycerin, vitamin B5. Liste complète sur le pot.$d$,
 $d$Matin et/ou soir sur visage et cou. Seul ou après un sérum.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '50 ml', 'France', 'Pot L''Oréal Revitalift Filler violet d''origine.',
 8500, null, 14, 'SHB-LO-RF50', '/products/loreal-filler.jpg?v=13',
 'sèche,normale,mature,déshydratée', null, false, true, true, true, 'L26-702', '2028-03-31'),

(101, 'neutrogena-collagen', 'Crème Collagen Bank', 35, 1,
 $d$Crème Neutrogena Collagen Bank 50 ml. Micro-peptides + bakuchiol (alternative au rétinol) : collagène, fermeté, élasticité. Non grasse. Tarif dm.de 12,95 €.$d$,
 $d$Aqua, bakuchiol, micro-peptide technology, glycerin. Sans parfum. Liste complète sur l'emballage.$d$,
 $d$Matin et/ou soir, une noisette. Le jour : terminer par un SPF.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '50 ml', 'États-Unis', 'Boîte Neutrogena Collagen Bank d''origine Johnson & Johnson.',
 8500, null, 16, 'SHB-NT-CB50', '/products/neutrogena-collagen.jpg?v=13',
 'normale,mixte,mature,tous', null, false, true, true, true, 'N26-018', '2028-04-30'),

(102, 'neutrogena-retinol', 'Sérum Retinol Boost', 35, 1,
 $d$Sérum Neutrogena Retinol Boost 30 ml. Rétinol pur + acide hyaluronique : ridules, taches, renouvellement. Formule d'entrée en rétinol. Tarif dm.de 14,95 €.$d$,
 $d$Aqua, retinol, hyaluronic acid, glycerin. Liste complète sur le flacon.$d$,
 $d$Soir, 3 gouttes sur peau propre. Commencer 2 soirs / semaine. Le matin : SPF obligatoire.$d$,
 $d$Usage externe. Rétinol : déconseillé grossesse / allaitement. Peut peler. Éviter le soleil sans SPF.$d$,
 '30 ml', 'États-Unis', 'Flacon Neutrogena Retinol Boost d''origine, scellé.',
 9800, null, 14, 'SHB-NT-RB30', '/products/neutrogena-retinol.jpg?v=13',
 'mature,normale,mixte,taches', null, false, true, false, true, 'N26-019', '2028-03-31'),

(103, 'garnier-wonder-tint', 'Wonder Tint Vitamine C LSF 50+', 30, 1,
 $d$Fluide teinté Garnier Vitamin C Wonder Tint 40 ml, LSF 50+. Vitamine C, niacinamide, 5 % glycérine : unifie, hydrate, protège. Fini naturel, vegan. Teinte claire. Tarif dm.de 12,95 €.$d$,
 $d$Aqua, vitamin C derivative, niacinamide, glycerin 5 %, UV filters. Vegan. Liste complète sur l'emballage.$d$,
 $d$Matin, seule ou après le sérum. Bien étaler. Renouveler en exposition.$d$,
 $d$Usage externe. Faire un test de teinte au poignet. La protection solaire ne remplace pas l'ombre.$d$,
 '40 ml LSF 50+', 'France', 'Boîte Garnier Wonder Tint d''origine, teinte claire, import dm.',
 8500, null, 16, 'SHB-GA-WT40', '/products/garnier-wonder-tint.jpg?v=13',
 'terne,mixte,normale,taches', null, true, true, true, true, 'G26-089', '2028-06-30'),

(104, 'garnier-glow-booster', 'Gel nettoyant Glow Booster Vit. C', 30, 1,
 $d$Gel nettoyant Garnier SkinActive Glow Booster vitamine C 250 ml. Enlève maquillage et impuretés, hydrate, teint plus frais. Vegan. Tarif dm.de 5,95 €.$d$,
 $d$Aqua, vitamin C derivative, glycerin, mild surfactants. Vegan. Liste complète sur le flacon.$d$,
 $d$Matin et soir, masser sur visage mouillé, rincer.$d$,
 $d$Éviter les yeux. Usage externe.$d$,
 '250 ml', 'France', 'Flacon Garnier Glow Booster jaune d''origine.',
 3900, null, 24, 'SHB-GA-GB250', '/products/garnier-glow-booster.jpg?v=13',
 'terne,normale,mixte,tous', null, false, true, true, true, 'G26-090', '2028-08-31'),

(105, 'balea-med-panthenol', 'MED baume 5 % panthénol', 29, 2,
 $d$Baume corps Balea MED Ultra Sensitive Panthenol 250 ml. 5 % panthénol, niacinamide, glycérine : calme démangeaisons, peaux très sensibles, bébés. Sans parfum. Tarif dm.de 2,65 €.$d$,
 $d$Aqua, panthenol 5 %, glycerin, niacinamide, shea butter, sunflower oil. Sans parfum, sans colorant. Liste complète sur le flacon.$d$,
 $d$Matin et soir sur corps, visages sensibles, plis. Convient aux enfants.$d$,
 $d$Usage externe. Ceci n'est pas un médicament. Éviter les plaies ouvertes.$d$,
 '250 ml', 'Allemagne', 'Flacon Balea MED Ultra Sensitive d''origine dm, lot photographié.',
 1750, null, 36, 'SHB-BL-PN250', '/products/balea-med-panthenol.jpg?v=13',
 'sensible,très sèche,sèche,enfant', null, false, true, true, true, 'D26-221', '2028-09-30'),

(106, 'herbal-fiji', 'Shampoing Fiji coco', 43, 3,
 $d$Shampoing Herbal Essences Fiji 250 ml. Coco + notes tropicales : volume léger, cheveux sans poids. Tarif rayon dm ~3,95 €.$d$,
 $d$Aqua, surfactants, coconut scent, conditioning agents. Liste complète sur le flacon.$d$,
 $d$Sur cheveux mouillés, masser le cuir, rincer. Suivre de l'après-shampoing Fiji.$d$,
 $d$Éviter les yeux. Usage externe.$d$,
 '250 ml', 'États-Unis', 'Flacon Herbal Essences Fiji vert d''origine, import dm.',
 2600, null, 28, 'SHB-HE-FJ250', '/products/herbal-fiji.jpg?v=13',
 null, 'fins,normaux,volume,tous', false, true, true, true, 'H26-088', '2028-09-30'),

(107, 'garnier-fructis-aloe', 'Fructis Aloe Hydra Bomb', 30, 3,
 $d$Shampoing Garnier Fructis Aloe Hydra Bomb 250 ml. Aloe vera : cheveux normaux à secs, hydratation sans silicones lourds. Tarif dm ~2,75 €.$d$,
 $d$Aqua, aloe vera, mild surfactants. Liste complète sur le flacon.$d$,
 $d$Sur cheveux mouillés, masser, rincer. Enchaîner avec Fructis Aloe après-shampoing.$d$,
 $d$Éviter les yeux. Usage externe.$d$,
 '250 ml', 'France', 'Flacon Garnier Fructis Aloe Hydra Bomb d''origine.',
 1800, null, 32, 'SHB-GA-AH250', '/products/garnier-fructis-aloe.jpg?v=13',
 null, 'secs,normaux,déshydratés', false, true, true, true, 'G26-091', '2028-09-30'),

(108, 'dejan-mask', 'Masque The Foundation', 44, 3,
 $d$Masque Dejan Garz The Foundation 200 ml. Soin profond, tous types : hydratation, démêlage, brillance. Texture crème, parfum salon. Tarif rayon dm 9,95 €.$d$,
 $d$Aqua, conditioning oils, proteins, glycerin. Liste complète sur le tube.$d$,
 $d$Après le shampoing, 3 à 5 minutes sur longueurs, rincer. 1 à 2 fois par semaine.$d$,
 $d$Éviter les yeux. Usage externe.$d$,
 '200 ml', 'Allemagne', 'Tube Dejan Garz The Foundation d''origine, import dm.',
 6550, null, 16, 'SHB-DG-TF200', '/products/dejan-mask.jpg?v=13',
 null, 'tous,secs,abîmés,normaux', true, true, true, true, 'J26-010', '2028-07-31'),

(109, 'dejan-oil', 'Huile Superstar Hair Oil', 44, 3,
 $d$Huile Dejan Garz Superstar 50 ml. Finition brillance, pointes, anti-frisottis. Quelques gouttes suffisent. Tarif rayon dm 8,95 €.$d$,
 $d$Light oils, shine agents, fragrance. Liste complète sur la boîte.$d$,
 $d$1 à 2 pompes sur pointes sèches, avant ou après le brushing. Éviter les racines grasses.$d$,
 $d$Usage externe. Éviter les yeux. Peut tacher les tissus clairs.$d$,
 '50 ml', 'Allemagne', 'Flacon Dejan Garz Superstar Hair Oil d''origine.',
 5850, null, 16, 'SHB-DG-SO50', '/products/dejan-oil.jpg?v=13',
 null, 'secs,abîmés,frisottis,tous', false, true, false, true, 'J26-011', '2028-07-31')

on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  ingredients = excluded.ingredients,
  usage_tips = excluded.usage_tips,
  precautions = excluded.precautions,
  format_label = excluded.format_label,
  price_xof = excluded.price_xof,
  image_url = excluded.image_url,
  skin_types = excluded.skin_types,
  hair_types = excluded.hair_types,
  is_featured = excluded.is_featured,
  is_new = true,
  is_bestseller = excluded.is_bestseller,
  is_active = true,
  stock = excluded.stock;

update site_settings
set value = 'Nouveau rayon dm · Acnemy, INAO, Nø, nerds, e.l.f. · tarif web x 656 F'
where key = 'announcement';

select setval('brands_id_seq', (select max(id) from brands));
select setval('products_id_seq', (select max(id) from products));
