-- Rayon dm (3e vague) : Geek & Gorgeous, hautsache, Nø All-In, Nivea Q10,
-- sebamed, S-O-S, Garnier Vit. C, L'Oréal Age Perfect, Balea Creme-Öl, Herbal, Dejan.
-- Prix = tarif dm.de × 656 XOF, arrondi 50 F.

insert into brands (id, slug, name, country, verified) values
  (45, 'nivea', 'Nivea', 'Allemagne', true),
  (46, 'sebamed', 'sebamed', 'Allemagne', true),
  (47, 'sos', 'S-O-S', 'Allemagne', true)
on conflict (slug) do nothing;

insert into products (
  id, slug, name, brand_id, category_id, description, ingredients, usage_tips, precautions,
  format_label, origin, authenticity_note, price_xof, compare_at_xof, stock, sku, image_url,
  skin_types, hair_types, is_featured, is_new, is_bestseller, is_active, lot_number, expires_on
) values

(110, 'elf-eye-cream', 'Crème contour Bright & Brew', 36, 1,
 $d$Crème contour des yeux e.l.f. Skin Bright & Brew-tiful Holy Hydration 15 g. Vitamine C + 3 % caféine : poches, cernes, glow immédiat. Texture légère, vegan. Tarif dm.de 14,95 €.$d$,
 $d$Aqua, caffeine 3 %, vitamin C derivative, glycerin, banana-tinted powder. Liste complète sur l'emballage.$d$,
 $d$Matin, une perle sur le contour, tapoter. Seule ou sous le correcteur.$d$,
 $d$Usage externe. Éviter l'intérieur de l'œil.$d$,
 '15 g', 'États-Unis', 'Pot e.l.f. Skin Bright & Brew d''origine, import dm.',
 9800, null, 16, 'SHB-EL-BB15', '/products/elf-eye-cream.jpg?v=14',
 'tous,cernes,mixte,normale', null, false, true, true, true, 'E26-303', '2028-06-30'),

(111, 'gg-porefectly', 'Sérum 101 Porefectly Clear', 41, 1,
 $d$Sérum Geek & Gorgeous 101 Porefectly Clear 30 ml. 2 % acide salicylique + sarcosine : pores, points noirs, excès de sébum. Gel léger, vegan, sans parfum. Tarif dm.de 7,35 €.$d$,
 $d$Aqua, salicylic acid 2 %, sarcosine, glycerin. Sans parfum. Liste complète sur le flacon.$d$,
 $d$Soir, 3 gouttes sur zones grasses. 1 soir sur 2 si peau sensible. Le jour : SPF.$d$,
 $d$Usage externe. Éviter les yeux. Peut piquer (BHA). Ne pas superposer d'autres acides au début.$d$,
 '30 ml', 'Hongrie', 'Flacon Geek & Gorgeous Porefectly Clear d''origine, import dm.',
 4800, null, 20, 'SHB-GG-PC30', '/products/gg-porefectly.jpg?v=14',
 'grasse,mixte,acneique,pores', null, true, true, true, true, 'G26-503', '2028-06-30'),

(112, 'gg-bbomb', 'Sérum 101 B-Bomb 10 % niacinamide', 41, 1,
 $d$Sérum Geek & Gorgeous 101 B-Bomb 30 ml. 10 % niacinamide + zinc PCA + sarcosine : pores, brillance, teint plus net. Léger, vegan, sans parfum. Tarif dm.de 8,35 €.$d$,
 $d$Aqua, niacinamide 10 %, zinc PCA, sarcosine, glycerin. Sans parfum. Liste complète sur le flacon.$d$,
 $d$Matin et/ou soir, 3 gouttes sur visage. Seul ou avant la crème.$d$,
 $d$Usage externe. Éviter les yeux. Introduire progressivement si 10 % est nouveau pour vous.$d$,
 '30 ml', 'Hongrie', 'Flacon Geek & Gorgeous B-Bomb d''origine, import dm.',
 5450, null, 20, 'SHB-GG-BB30', '/products/gg-bbomb.jpg?v=14',
 'grasse,mixte,pores,terne', null, true, true, true, true, 'G26-504', '2028-06-30'),

(113, 'gg-stress', 'Sérum 101 Stress Less', 41, 1,
 $d$Sérum Geek & Gorgeous 101 Stress Less 30 ml. 0,2 % bêta-glucane d'avoine + 0,3 % madécassoside : calme, répare, peaux sensibles ou après un acide. Gel, vegan. Tarif dm.de 11,35 €.$d$,
 $d$Aqua, beta-glucan 0,2 %, madecassoside 0,3 %, glycerin, saccharide isomerate. Liste complète sur le flacon.$d$,
 $d$Matin et soir, 3 gouttes sur peau propre, surtout après un exfoliant.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '30 ml', 'Hongrie', 'Flacon Geek & Gorgeous Stress Less d''origine, import dm.',
 7450, null, 16, 'SHB-GG-SL30', '/products/gg-stress.jpg?v=14',
 'sensible,rougeurs,mixte,barrière', null, false, true, false, true, 'G26-505', '2028-06-30'),

(114, 'gg-apad', 'Sérum 101 aPAD', 41, 1,
 $d$Sérum Geek & Gorgeous 101 aPAD 30 ml. Dérivé d'acide azélaïque (potassium azeloyl diglycinate) : rougeurs, boutons, taches, rosacea-prone. Vegan, sans parfum. Tarif dm.de 11,35 €.$d$,
 $d$Aqua, potassium azeloyl diglycinate, glycerin. Sans parfum. Liste complète sur le flacon.$d$,
 $d$Matin et/ou soir, 3 gouttes. Compatible avec niacinamide et hydratant.$d$,
 $d$Usage externe. Éviter les yeux. Ceci n'est pas un médicament.$d$,
 '30 ml', 'Hongrie', 'Flacon Geek & Gorgeous aPAD d''origine, import dm.',
 7450, null, 16, 'SHB-GG-AP30', '/products/gg-apad.jpg?v=14',
 'acneique,rougeurs,mixte,taches', null, true, true, false, true, 'G26-506', '2028-06-30'),

(115, 'hautsache-feucht', 'Sérum hydratant', 42, 1,
 $d$Sérum hautsache Feuchtigkeit 30 ml (dm × fraubeauty). Acide hyaluronique : soif, rebond, base de routine. Vegan, sans parfum. Tarif dm.de 7,95 €.$d$,
 $d$Aqua, sodium hyaluronate, glycerin, panthenol. Sans parfum. Liste complète sur l'emballage.$d$,
 $d$Matin et soir, quelques gouttes sur peau encore humide, avant la crème.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '30 ml', 'Allemagne', 'Boîte hautsache Feuchtigkeitsserum d''origine dm.',
 5200, null, 22, 'SHB-HS-FE30', '/products/hautsache-feucht.jpg?v=14',
 'déshydratée,normale,sèche,tous', null, false, true, true, true, 'H26-302', '2028-08-31'),

(116, 'hautsache-retinal', 'Sérum Retinal 0,1 %', 42, 1,
 $d$Sérum hautsache Retinal 30 ml. 0,1 % rétinal + 1 % vitamine E : ridules, grain, éclat — forme de vitamine A plus tolérée que le rétinol. Sans parfum, vegan. Tarif dm.de 8,95 €.$d$,
 $d$Aqua, retinal 0,1 %, tocopherol 1 %, glycerin. Sans parfum. Liste complète sur l'emballage.$d$,
 $d$Soir, 3 gouttes. Commencer 2 soirs / semaine. Le matin : SPF obligatoire.$d$,
 $d$Usage externe. Rétinal (vitamine A) : déconseillé grossesse / allaitement. Peut peler. Éviter le soleil sans SPF.$d$,
 '30 ml', 'Allemagne', 'Boîte hautsache Retinal Serum d''origine dm.',
 5850, null, 16, 'SHB-HS-RE30', '/products/hautsache-retinal.jpg?v=14',
 'mature,normale,mixte,taches', null, true, true, false, true, 'H26-303', '2028-07-31'),

(117, 'hautsache-tagescreme', 'Crème jour LSF 50+', 42, 1,
 $d$Crème hautsache jour 50 ml, LSF 50+. Filtres UVA/UVB + 0,5 % céramides : solaire quotidien, barrière, sans graisser. Vegan, sans parfum. Tarif dm.de 8,95 €.$d$,
 $d$Aqua, UV filters, ceramide NP 0,5 %, panthenol, sodium hyaluronate. Sans parfum. Liste complète sur l'emballage.$d$,
 $d$Dernière étape du matin : une noisette généreuse. Renouveler en exposition.$d$,
 $d$Usage externe. La protection solaire ne remplace pas l'ombre ni le chapeau.$d$,
 '50 ml LSF 50+', 'Allemagne', 'Boîte hautsache Tagescreme d''origine dm.',
 5850, null, 18, 'SHB-HS-TC50', '/products/hautsache-tagescreme.jpg?v=14',
 'tous,sensible,normale,mixte', null, true, true, true, true, 'H26-304', '2028-07-31'),

(118, 'no-allin-serum', 'Sérum All-In Barrier', 39, 1,
 $d$Sérum Nø Cosmetics All-In Barrier 20 ml. Eau minérale marine, algues, inuline prébiotique : microbiome, barrière, peaux sensibles. Tarif dm.de 16,95 €.$d$,
 $d$Aqua, sea mineral water, algae extracts, inulin, glycerin. Liste complète sur l'emballage.$d$,
 $d$Matin et soir, 3 pompes sur peau propre, avant la crème.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '20 ml', 'Allemagne', 'Boîte Nø All-In Barrier Serum d''origine, import dm.',
 11100, null, 12, 'SHB-NO-AB20', '/products/no-allin-serum.jpg?v=14',
 'sensible,sèche,barrière,tous', null, false, true, false, true, 'O26-205', '2028-05-31'),

(119, 'nivea-q10', 'Crème Q10 Power extra-lift LSF 15', 45, 1,
 $d$Crème Nivea Q10 Power Extra Straffend 50 ml, LSF 15. Q10 + booster collagène : ridules, fermeté, hydratation 24 h. Tarif dm.de 12,95 €.$d$,
 $d$Aqua, ubiquinone (Q10), creatine, glycerin, UV filters. Liste complète sur le pot.$d$,
 $d$Matin, une noisette sur visage et cou. Éviter le contour des yeux.$d$,
 $d$Usage externe. LSF 15 n'est pas un solaire sport — compléter en plein soleil.$d$,
 '50 ml LSF 15', 'Allemagne', 'Pot Nivea Q10 Power d''origine Beiersdorf, import dm.',
 8500, null, 18, 'SHB-NV-Q1050', '/products/nivea-q10.jpg?v=14',
 'mature,normale,sèche,mixte', null, true, true, true, true, 'V26-101', '2028-04-30'),

(120, 'sebamed-clear-foam', 'Mousse Clear Face', 46, 1,
 $d$Mousse sebamed Clear Face 150 ml. pH 5,5 + Montaline C40 + panthénol : nettoie les peaux grasses à boutons, sans savon. Tarif dm.de 6,95 €.$d$,
 $d$Aqua, Montaline C40, panthenol, mild surfactants. pH 5,5. Liste complète sur le flacon.$d$,
 $d$Matin et soir sur visage mouillé, mousser, rincer. Suivre d'une crème non comédogène.$d$,
 $d$Usage externe. Éviter les yeux. Ceci n'est pas un médicament.$d$,
 '150 ml', 'Allemagne', 'Flacon sebamed Clear Face d''origine, import dm.',
 4550, null, 20, 'SHB-SB-CF150', '/products/sebamed-clear-foam.jpg?v=14',
 'grasse,mixte,acneique', null, false, true, true, true, 'S26-080', '2028-08-31'),

(121, 'sos-antipickel', 'Crème Anti-Pickel Akut', 47, 1,
 $d$Crème S-O-S Anti-Pickel Akut 50 ml. Soin d'urgence boutons : régule le sébum, assèche, calme. Tarif dm.de 6,95 €.$d$,
 $d$Aqua, sebum-regulating complex, soothing agents. Liste complète sur l'emballage.$d$,
 $d$Matin et soir sur peau propre, ciblé sur les boutons ou en couche fine.$d$,
 $d$Usage externe. Ceci n'est pas un médicament. Patch-test 24 h.$d$,
 '50 ml', 'Allemagne', 'Tube S-O-S Anti-Pickel Akut d''origine, import dm.',
 4550, null, 18, 'SHB-SO-AP50', '/products/sos-antipickel.jpg?v=14',
 'acneique,grasse,mixte', null, false, true, false, true, 'Z26-011', '2028-07-31'),

(122, 'garnier-vitc-serum', 'Sérum Glow Booster Vitamine C', 30, 1,
 $d$Sérum Garnier SkinActive Glow Booster vitamine C 30 ml. Vitamine C, niacinamide, acide salicylique : taches, glow, grain. Vegan. Tarif dm.de 11,95 €.$d$,
 $d$Aqua, vitamin C derivative, niacinamide, salicylic acid, citrus extract. Vegan. Liste complète sur le flacon.$d$,
 $d$Matin et/ou soir, 3 gouttes sur visage. Le jour : terminer par un SPF.$d$,
 $d$Usage externe. Éviter les yeux. Peut piquer (salicylique) sur peau lésée.$d$,
 '30 ml', 'France', 'Flacon Garnier Glow Booster Serum d''origine, import dm.',
 7850, null, 20, 'SHB-GA-VS30', '/products/garnier-vitc-serum.jpg?v=14',
 'terne,taches,mixte,normale', null, true, true, true, true, 'G26-092', '2028-06-30'),

(123, 'garnier-vitc-spf', 'Fluide Vitamine C LSF 50+', 30, 1,
 $d$Fluide Garnier SkinActive vitamine C Invisible LSF 50+, 40 ml. Protège, hydrate, prévient les taches. Fini invisible, vegan. Tarif dm.de 12,95 €.$d$,
 $d$Aqua, vitamin C derivative, UV filters, glycerin, peptides. Vegan. Liste complète sur l'emballage.$d$,
 $d$Matin, dernière étape : une noisette généreuse. Renouveler en exposition.$d$,
 $d$Usage externe. La protection solaire ne remplace pas l'ombre.$d$,
 '40 ml LSF 50+', 'France', 'Boîte Garnier Vitamin C Daily UV LSF 50+ d''origine.',
 8500, null, 18, 'SHB-GA-SP40', '/products/garnier-vitc-spf.jpg?v=14',
 'tous,terne,taches,mixte', null, true, true, true, true, 'G26-093', '2028-06-30'),

(124, 'loreal-vitc-glow', 'Crème Revitalift Clinical Vit. C Glow', 40, 1,
 $d$Crème L'Oréal Paris Revitalift Clinical Vitamin C Glow 50 ml. Vitamine C + acide salicylique : pores, éclat, ridules, hydratation 24 h. Tarif dm.de 17,95 €.$d$,
 $d$Aqua, vitamin C, salicylic acid, glycerin, light-reflecting pigments. Liste complète sur le pot.$d$,
 $d$Matin, une noisette sur visage. Terminer par un SPF.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '50 ml', 'France', 'Pot L''Oréal Revitalift Clinical Vitamin C Glow d''origine.',
 11750, null, 12, 'SHB-LO-VC50', '/products/loreal-vitc-glow.jpg?v=14',
 'terne,mature,mixte,normale', null, false, true, false, true, 'L26-703', '2028-03-31'),

(125, 'loreal-age-perfect', 'Sérum Age Perfect collagène', 40, 1,
 $d$Sérum L'Oréal Paris Age Perfect 30 ml. Peptides collagène : fermeté, relâchement, peaux matures 50+. Tarif rayon dm ~12,95 €.$d$,
 $d$Aqua, collagen peptides, glycerin, niacinamide. Liste complète sur le flacon.$d$,
 $d$Matin et soir, 3-4 gouttes sur visage et cou, avant la crème Age Perfect.$d$,
 $d$Usage externe. Éviter les yeux.$d$,
 '30 ml', 'France', 'Flacon L''Oréal Age Perfect d''origine, import dm.',
 8500, null, 12, 'SHB-LO-AP30', '/products/loreal-age-perfect.jpg?v=14',
 'mature,sèche,normale', null, false, true, false, true, 'L26-704', '2028-03-31'),

(126, 'balea-med-cremeol', 'MED lait Crème-Huile', 29, 2,
 $d$Lait Balea MED Crème-Huile 400 ml. Allantoïne + glycérine : peaux sèches et sensibles, 48 h d'hydratation, sans parabène. Tarif dm.de 1,75 €.$d$,
 $d$Aqua, sunflower oil, glycerin, allantoin, isopropyl palmitate. Liste complète sur le flacon.$d$,
 $d$Matin et soir sur le corps, peaux sèches. Une noisette suffit — texture lait-huile.$d$,
 $d$Usage externe. Ceci n'est pas un médicament.$d$,
 '400 ml', 'Allemagne', 'Flacon Balea MED Creme-Öl d''origine dm, lot photographié.',
 1150, null, 40, 'SHB-BL-CO400', '/products/balea-med-cremeol.jpg?v=14',
 'sèche,sensible,très sèche', null, false, true, true, true, 'D26-222', '2028-09-30'),

(127, 'herbal-aloe', 'Shampoing Aloe Vera', 43, 3,
 $d$Shampoing Herbal Essences Feuchtigkeit Aloe Vera 350 ml. Aloe : cheveux secs, cuir apaisé, sans silicone ni sulfate. Tarif dm.de 3,95 €.$d$,
 $d$Aqua, aloe barbadensis leaf juice, mild surfactants. Sans silicone, sans sulfate. Liste complète sur le flacon.$d$,
 $d$Sur cheveux mouillés, masser, rincer. Suivre de l'après-shampoing Aloe Vera.$d$,
 $d$Éviter les yeux. Usage externe.$d$,
 '350 ml', 'États-Unis', 'Flacon Herbal Essences Aloe Vera d''origine, import dm.',
 2600, null, 28, 'SHB-HE-AV350', '/products/herbal-aloe.jpg?v=14',
 null, 'secs,bouclés,déshydratés,cuir sensible', false, true, true, true, 'H26-089', '2028-09-30'),

(128, 'herbal-argan', 'Shampoing Argan Maroc', 43, 3,
 $d$Shampoing Herbal Essences Repair Arganöl 350 ml. Argan marocain : cheveux abîmés, brillance, réparation. Tarif dm.de 3,95 €.$d$,
 $d$Aqua, argan oil, surfactants, conditioning agents. Liste complète sur le flacon.$d$,
 $d$Sur cheveux mouillés, masser, rincer. Enchaîner avec l'après-shampoing Argan.$d$,
 $d$Éviter les yeux. Usage externe.$d$,
 '350 ml', 'États-Unis', 'Flacon Herbal Essences Argan d''origine, import dm.',
 2600, null, 24, 'SHB-HE-AR350', '/products/herbal-argan.jpg?v=14',
 null, 'abîmés,secs,colorés,tous', false, true, false, true, 'H26-090', '2028-09-30'),

(129, 'dejan-shampoo', 'Shampoing The Foundation', 44, 3,
 $d$Shampoing Dejan Garz The Foundation 300 ml. Nettoie en profondeur (résidus de coiffage) sans alourdir, anti-frisottis à la racine, panthénol. Tous types. Tarif dm.de 9,95 €.$d$,
 $d$Aqua, surfactants, panthenol, salicylic acid, glycerin, sodium hyaluronate. Vegan. Liste complète sur le flacon.$d$,
 $d$Sur cheveux mouillés, masser le cuir, rincer. Suivre du masque The Foundation.$d$,
 $d$Éviter les yeux. Usage externe.$d$,
 '300 ml', 'Allemagne', 'Flacon pompe Dejan Garz The Foundation d''origine, import dm.',
 6550, null, 16, 'SHB-DG-SH300', '/products/dejan-shampoo.jpg?v=14',
 null, 'tous,gras,abîmés,frisottis', true, true, true, true, 'J26-012', '2028-07-31')

on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  ingredients = excluded.ingredients,
  usage_tips = excluded.usage_tips,
  precautions = excluded.precautions,
  format_label = excluded.format_label,
  price_xof = excluded.price_xof,
  image_url = excluded.image_url,
  skin_types = excluded.skin_types,
  hair_types = excluded.hair_types,
  is_featured = excluded.is_featured,
  is_new = true,
  is_bestseller = excluded.is_bestseller,
  is_active = true,
  stock = excluded.stock;

update site_settings
set value = 'Nouveau rayon dm · Acnemy, INAO, Nø, nerds, G&G, Nivea Q10 · tarif web x 656 F'
where key = 'announcement';

select setval('brands_id_seq', (select max(id) from brands));
select setval('products_id_seq', (select max(id) from products));
