-- Vague K-beauty authentique : K-Secret Seoul 1988, AXIS-Y, Round Lab,
-- Aestura, SKIN1004, Beauty of Joseon, celimax, Medicube, Anua.
-- Packshots officiels. Prix Lomé circuit UMMA / officinal, arrondis 100 F.

insert into brands (id, slug, name, country, verified) values
  (60, 'k-secret', 'K-Secret', 'Corée', true),
  (61, 'aestura', 'Aestura', 'Corée', true),
  (62, 'celimax', 'celimax', 'Corée', true)
on conflict (slug) do nothing;

insert into products (
  id, slug, name, brand_id, category_id, description, ingredients, usage_tips, precautions,
  format_label, origin, authenticity_note, price_xof, compare_at_xof, stock, sku, image_url,
  skin_types, hair_types, is_featured, is_new, is_bestseller, is_active, lot_number, expires_on
) values

(175, 'k-secret-seoul-foam', 'Mousse Seoul 1988 Pine Cica', 60, 1,
 $d$Mousse nettoyante K-Secret Seoul 1988 Cleansing Foam, Pine Cica 1 % + probiotiques, 150 ml. Lave sans tirer : cica de pin, ferments. Le premier geste du soir après l'harmattan, peaux sensibles ou à rougeurs. Texture crème-mousse, 150 ml famille.$d$,
 $d$Aqua, pinus densiflora extract, centella asiatica, lactobacillus ferment, glycerin, mild surfactants. Liste complète sur le tube.$d$,
 $d$Matin et/ou soir, sur peau mouillée, une noisette, masser 30 secondes, rincer. Relais d'une huile si SPF très résistant.$d$,
 $d$Usage externe. Éviter les yeux. Patch-test si barrière lésée. Ceci n'est pas un médicament.$d$,
 '150 ml', 'Corée', 'Tube K-Secret Seoul 1988 d''origine, circuit UMMA / importateur vérifié, lot photographié.',
 8900, null, 24, 'SHB-KS-CF150', '/products/k-secret-seoul-foam.jpg?v=25',
 'sensible,normale,mixte,sèche,irritée', null, true, true, false, true, 'K26-198', '2028-06-30'),

(176, 'k-secret-seoul-capsule', 'Crème capsules Seoul 1988 Yuja', 60, 1,
 $d$Crème K-Secret Seoul 1988 Capsule Cream, niacinamide 5 % + yuja, 50 ml. Capsules d'éclat dans une gelée-crème : teint plus uni, hydratation dew. La crème du soir pour taches et teint terne — sans hydroquinone.$d$,
 $d$Aqua, niacinamide 5 %, citrus junos (yuja) extract, glycerin, squalane. Liste complète sur le pot.$d$,
 $d$Soir, une noisette sur visage et cou. Le jour : solaire obligatoire (Relief Sun, Zero-cast ou Anthelios).$d$,
 $d$Usage externe. Ne pas présenter comme un éclaircissant. Patch-test. Ceci n'est pas un médicament.$d$,
 '50 ml', 'Corée', 'Pot K-Secret Seoul 1988 d''origine, capsules visibles, lot contrôlé à réception.',
 12900, null, 18, 'SHB-KS-CC50', '/products/k-secret-seoul-capsule.jpg?v=25',
 'terne,mixte,normale,sèche,sensible', null, true, true, true, true, 'K26-YJA', '2028-05-31'),

(177, 'k-secret-seoul-eye', 'Contour des yeux Seoul 1988 Rétinal', 60, 1,
 $d$Crème contour des yeux K-Secret Seoul 1988, rétinal liposome 4 % + haricot fermenté, 30 ml. Cible ridules et manque d'éclat du contour. Texture baume-crème, tube 30 ml. Introduire lentement : le rétinal n'est pas un rétinol « débutant ».$d$,
 $d$Aqua, retinal liposome 4 %, fermented bean extract, peptides, glycerin. Liste complète sur le tube.$d$,
 $d$Soir uniquement, un grain de riz sous l'œil, en tapotant. Commencer 2 soirs par semaine. Le jour : SPF.$d$,
 $d$Ne pas utiliser enceinte ou allaitante. Éviter la muqueuse. Peut piquer. Patch-test 24 h. Ceci n'est pas un médicament.$d$,
 '30 ml', 'Corée', 'Tube K-Secret Seoul 1988 Eye Cream d''origine, lot photographié.',
 11900, null, 16, 'SHB-KS-EY30', '/products/k-secret-seoul-eye.jpg?v=25',
 'normale,sèche,mixte,mature', null, true, true, false, true, 'K26-EY4', '2028-04-30'),

(178, 'k-secret-seoul-serum', 'Sérum Seoul 1988 Rétinal + ginseng noir', 60, 1,
 $d$Sérum K-Secret Seoul 1988, rétinal liposome 2 % + ginseng noir, 30 ml. Renouvellement visible, éclat, texture fluide jaune. Le sérum du soir pour qui a déjà un rétinol doux. Flacon pompe 30 ml.$d$,
 $d$Aqua, retinal liposome 2 %, panax ginseng (black) extract, niacinamide, squalane. Liste complète sur le flacon.$d$,
 $d$Soir, 2 pompes sur visage (pas le contour). Introduire un soir sur deux. Ne pas superposer AHA/BHA le même soir. SPF le matin.$d$,
 $d$Ne pas utiliser enceinte ou allaitante. Peut piquer et desquamer. Patch-test. Ceci n'est pas un médicament.$d$,
 '30 ml', 'Corée', 'Flacon pompe K-Secret Seoul 1988 Serum d''origine, circuit vérifié.',
 14900, null, 14, 'SHB-KS-SR30', '/products/k-secret-seoul-serum.jpg?v=25',
 'normale,mixte,terne,mature', null, true, true, true, true, 'K26-SR2', '2028-04-30'),

(179, 'axis-y-physical-sun', 'Solaire minéral No-Stress SPF50+', 13, 1,
 $d$AXIS-Y Complete No-Stress Physical Sunscreen SPF50+ PA++++ Ver. 3, 50 ml. Filtres minéraux, armoise, niacinamide 2 %, squalane. Formule 6+1+1, fini confortable, peu de film blanc. Le solaire quotidien peaux sensibles / acnéiques.$d$,
 $d$Zinc oxide, titanium dioxide, mugwort extract, niacinamide 2 %, squalane. Filtres minéraux. Liste complète sur le tube.$d$,
 $d$Dernière étape du matin : 1/3 de cuillère à café visage + cou. Renouveler toutes les 2 h en plein soleil.$d$,
 $d$Usage externe. La protection solaire ne remplace pas l'ombre ni le chapeau. Peut laisser un voile sur peaux très foncées — estomper.$d$,
 '50 ml', 'Corée', 'Tube AXIS-Y Complete No-Stress Ver. 3 d''origine, applicateur, lot photographié.',
 14500, null, 22, 'SHB-AX-NS50', '/products/axis-y-physical-sun.jpg?v=25',
 'sensible,acneique,mixte,normale,tous', null, true, true, true, true, 'X26-NS3', '2028-03-31'),

(180, 'round-lab-pine-cica', 'Nettoyant Pine Calming Cica', 10, 1,
 $d$Round Lab Pine Calming Cica Cleanser 150 ml. Pin + cica : lave les peaux sensibles, tiraillements, rougeurs. Texture gel-crème, tube illustré 150 ml. Le second nettoyage du soir quand le Low pH COSRX décape trop.$d$,
 $d$Pinus densiflora leaf extract, centella asiatica, madecassoside, panthenol, glycerin. Liste complète sur le tube.$d$,
 $d$Soir, sur peau mouillée, une noisette, masser, rincer. Peut servir seul le matin.$d$,
 $d$Usage externe. Éviter les yeux. Patch-test si barrière très lésée.$d$,
 '150 ml', 'Corée', 'Tube Round Lab Pine Calming Cica d''origine, boîte, lot contrôlé.',
 10900, null, 20, 'SHB-RL-PC150', '/products/round-lab-pine-cica.jpg?v=25',
 'sensible,sèche,normale,irritée,mixte', null, true, true, false, true, 'R26-PC1', '2028-07-31'),

(181, 'aestura-atobarrier-365', 'Crème Atobarrier 365', 61, 1,
 $d$Aestura Atobarrier 365 Cream DermaON, 80 ml. Crème barrière pharmacie coréenne (Amorepacific) : céramides, cholestérol, acides gras. Peaux sèches, sensibles, atopiques. Le relais du CeraVe / Cicaplast en texture coréenne, tube 80 ml.$d$,
 $d$Aqua, glycerin, ceramide NP, cholesterol, fatty acids, DermaON. Sans parfum agressif. Liste complète sur le tube.$d$,
 $d$Matin et/ou soir, une noisette sur visage et cou. Le jour : solaire par-dessus. Corps localisé sur plaques sèches.$d$,
 $d$Usage externe. Ceci n'est pas un médicament. Eczéma sévère : avis d'un professionnel de santé. Éviter les yeux.$d$,
 '80 ml', 'Corée', 'Tube Aestura Atobarrier 365 d''origine Amorepacific, circuit officinal / UMMA, lot photographié.',
 18900, null, 14, 'SHB-AE-AB80', '/products/aestura-atobarrier-365.jpg?v=25',
 'sèche,très sèche,sensible,atopique,normale', null, true, true, true, true, 'E26-365', '2028-08-31'),

(182, 'skin1004-toning-toner', 'Toner Madagascar Centella 400 ml', 9, 1,
 $d$SKIN1004 Madagascar Centella Toning Toner 400 ml. Eau de centella de Madagascar, format familial. Apaise, hydrate, prépare aux sérums. Le grand frère de l'ampoule déjà au rayon — cotons ou mains.$d$,
 $d$Centella asiatica extract (Madagascar), panthenol, hyaluronic acid, aqua. Liste complète sur le flacon.$d$,
 $d$Matin et soir, imprégner un coton ou tapoter avec les mains. Compresses 5 min sur zones rouges.$d$,
 $d$Usage externe. Conserver à l'abri de la chaleur. Patch-test si peau très réactive.$d$,
 '400 ml', 'Corée', 'Flacon SKIN1004 Madagascar Centella Toning Toner d''origine, lot photographié.',
 13900, null, 18, 'SHB-S1-TT400', '/products/skin1004-toning-toner.jpg?v=25',
 'sensible,acneique,mixte,normale,irritée,tous', null, true, true, true, true, 'S26-TT4', '2028-06-30'),

(183, 'boje-apricot-peeling', 'Gel peeling Fleur d''abricot', 4, 1,
 $d$Beauty of Joseon Apricot Blossom Peeling Gel, tube 120 ml. Gomme chimique-enzymatique douce : cellules mortes, teint terne, sans grains qui rayent. 1 à 2 fois par semaine — le relais du Glow Serum.$d$,
 $d$Prunus armeniaca (apricot) extract, cellulose, plant-derived cellulose, aqua. Liste complète sur le tube.$d$,
 $d$Sur peau propre sèche, une noisette, masser 30 à 60 s jusqu'aux « peluches », rincer. Max 2 fois / semaine. Pas le même soir qu'un acide fort.$d$,
 $d$Usage externe. Éviter les yeux et les peaux lésées. SPF le lendemain. Ceci n'est pas un médicament.$d$,
 '120 ml', 'Corée', 'Tube Beauty of Joseon Apricot Blossom Peeling Gel d''origine, lot photographié.',
 11900, null, 16, 'SHB-BJ-AP120', '/products/boje-apricot-peeling.jpg?v=25',
 'terne,normale,mixte,sèche', null, true, true, false, true, 'J26-AP12', '2028-05-31'),

(184, 'celimax-noni-cream', 'Crème Noni Energy Repair', 62, 1,
 $d$celimax The Real Noni Energy Repair Cream 50 ml. Noni (Morinda) : réparation, confort, barrière. Texture gel-crème verte, tube 50 ml. Dernière étape du soir pour peaux fatiguées, déshydratées.$d$,
 $d$Morinda citrifolia (noni) extract, panthenol, ceramides, glycerin, aqua. Liste complète sur le tube.$d$,
 $d$Soir, une noisette sur visage et cou. Le jour : peut se porter sous le solaire si la peau n'est pas trop riche.$d$,
 $d$Usage externe. Éviter les yeux. Patch-test. Ceci n'est pas un médicament.$d$,
 '50 ml', 'Corée', 'Tube celimax Noni Cream d''origine, lot photographié à réception.',
 14500, null, 14, 'SHB-CL-NC50', '/products/celimax-noni-cream.jpg?v=25',
 'sèche,sensible,normale,déshydratée', null, true, true, false, true, 'C26-NN50', '2028-06-30'),

(185, 'boje-ginseng-essence', 'Essence Water Ginseng', 4, 1,
 $d$Beauty of Joseon Ginseng Essence Water, 150 ml. Eau-essence au ginseng : hydratation, éclat, préparation de la Dynasty Cream. Texture aqueuse, flacon 150 ml. L'étape entre toner et sérum.$d$,
 $d$Panax ginseng root extract, niacinamide, hyaluronic acid, aqua. Liste complète sur le flacon.$d$,
 $d$Après le toner, 3 à 4 gouttes ou une noisette dans les mains, tapoter. Suivre du Glow Serum ou de la Dynasty.$d$,
 $d$Usage externe. Éviter les yeux. Conserver à l'abri de la lumière.$d$,
 '150 ml', 'Corée', 'Flacon Beauty of Joseon Ginseng Essence Water d''origine, lot photographié.',
 14500, null, 16, 'SHB-BJ-GE150', '/products/boje-ginseng-essence.jpg?v=25',
 'normale,sèche,mixte,terne,sensible', null, true, true, true, true, 'J26-GE15', '2028-05-31'),

(186, 'medicube-triple-collagen', 'Crème Triple Collagen', 1, 1,
 $d$Medicube Triple Collagen Cream 50 ml. Collagène + niacinamide + élastine hydrolysée. Pot 50 ml, texture baume-crème. Fermeté visuelle, hydratation, éclat — le relais de la Collagen Night Wrapping Mask déjà au rayon.$d$,
 $d$Hydrolyzed collagen, niacinamide, hydrolyzed elastin, peptides, aqua. Liste complète sur le pot.$d$,
 $d$Soir, une noisette sur visage et cou. Le jour : possible sous le solaire si peau sèche.$d$,
 $d$Usage externe. Circuit APR / Medicube uniquement. Patch-test. Ceci n'est pas un médicament.$d$,
 '50 ml', 'Corée', 'Pot Medicube Triple Collagen d''origine, circuit APR / Medicube, hologramme et lot photographiés.',
 21900, null, 12, 'SHB-MD-TC50', '/products/medicube-triple-collagen.jpg?v=25',
 'normale,sèche,mixte,terne,mature', null, true, true, true, true, 'M26-TC50', '2028-03-31'),

(187, 'anua-azelaic-hyaluron', 'Sérum Azelaic Acid 10 + Hyaluron', 3, 1,
 $d$Anua Azelaic Acid 10 + Hyaluron Redness Soothing Serum, 30 ml. Acide azélaïque 10 % + HA : rougeurs, imperfections, teint irrégulier. Texture fluide, flacon 30 ml. Le sérum « calme » du Heartleaf déjà au rayon.$d$,
 $d$Azelaic acid 10 %, hyaluronic acid, houttuynia, panthenol, aqua. Liste complète sur le flacon.$d$,
 $d$Soir, 3 à 4 gouttes sur peau propre. Introduire un soir sur deux. SPF le jour. Ne pas superposer un peel AHA le même soir.$d$,
 $d$Peut piquer. Patch-test. Ne pas présenter comme un médicament anti-rosacée. Usage externe.$d$,
 '30 ml', 'Corée', 'Flacon Anua Azelaic Acid 10 Hyaluron d''origine, lot photographié.',
 16500, null, 18, 'SHB-AN-AZ30', '/products/anua-azelaic-hyaluron.jpg?v=25',
 'sensible,acneique,mixte,rougeurs,normale', null, true, true, true, true, 'N26-AZ10', '2028-04-30'),

(188, 'medicube-red-acne-peel', 'Peel Red Acne acide succinique', 1, 1,
 $d$Medicube Red Acne Succinic Acid Peel, 40 g. Acide succinique + AHA + BHA. Peel express 1 min pour peaux à imperfections : grain, points noirs, relief. Pas un quotidien — 1 à 2 fois / semaine, circuit APR uniquement.$d$,
 $d$Succinic acid, AHA, BHA, aqua. Liste complète sur le flacon et la boîte.$d$,
 $d$Soir, sur peau propre sèche, une couche, laisser 1 minute, rincer. Max 2 fois / semaine. SPF le lendemain. Pas le même soir qu'un rétinal.$d$,
 $d$Peel acide : pique, peut desquamer. Éviter peaux lésées, eczéma, grossesse. Patch-test 24 h. Circuit APR / Medicube uniquement. Ceci n'est pas un médicament.$d$,
 '40 g', 'Corée', 'Flacon Medicube Red Acne Succinic Acid Peel d''origine, boîte, hologramme, lot photographié. Zéro marketplace gris.',
 19900, null, 10, 'SHB-MD-RP40', '/products/medicube-red-acne-peel.jpg?v=25',
 'acneique,grasse,mixte', null, true, true, false, true, 'M26-RP40', '2028-02-28'),

(189, 'skin1004-tone-foam', 'Mousse Tone Brightening Centella', 9, 1,
 $d$SKIN1004 Madagascar Centella Tone Brightening Cleansing Gel Foam, 125 ml. Gel-mousse à la centella : lave, teint plus net, sans décaper. Le nettoyant du matin quand on porte le Hyalu-Cica Sun.$d$,
 $d$Centella asiatica extract, niacinamide, mild surfactants, aqua. Liste complète sur le tube.$d$,
 $d$Matin et/ou soir, une noisette sur peau mouillée, masser, rincer. Second nettoyage après l'huile Light Cleansing Oil.$d$,
 $d$Usage externe. Éviter les yeux. Ne pas présenter comme un éclaircissant.$d$,
 '125 ml', 'Corée', 'Tube SKIN1004 Tone Brightening Cleansing Gel Foam d''origine, lot photographié.',
 10900, null, 20, 'SHB-S1-TF125', '/products/skin1004-tone-foam.jpg?v=25',
 'terne,mixte,normale,sensible,tous', null, true, true, false, true, 'S26-TF12', '2028-07-31'),

(190, 'skin1004-tea-trica', 'Ampoule Tea-Trica Relief', 9, 1,
 $d$SKIN1004 Madagascar Centella Tea-Trica Relief Ampoule, 100 ml. Centella + tea tree : peaux à imperfections, pores, rougeurs. Texture aqueuse, grand format 100 ml. Le jumeau « acné » de l'ampoule Centella classique.$d$,
 $d$Centella asiatica extract, tea tree extract, niacinamide, panthenol, aqua. Liste complète sur le flacon.$d$,
 $d$Soir, 3 à 4 gouttes ou une pipette sur zones à imperfections. Peut se porter sur tout le visage si mixte. SPF le jour.$d$,
 $d$Contient du tea tree : peut piquer. Patch-test. Usage externe. Ceci n'est pas un médicament anti-acné.$d$,
 '100 ml', 'Corée', 'Flacon SKIN1004 Tea-Trica Relief Ampoule d''origine, lot photographié.',
 15900, null, 16, 'SHB-S1-TT100', '/products/skin1004-tea-trica.jpg?v=25',
 'acneique,grasse,mixte,sensible,pores', null, true, true, true, true, 'S26-TR10', '2028-05-31'),

(191, 'medicube-pdrn-capsule', 'Crème capsules PDRN Pink Collagen', 1, 1,
 $d$Medicube PDRN Pink Collagen Capsule Cream, 55 g. PDRN (sodium DNA) + niacinamide 5 %, capsules dans une gelée rose. Hydratation, éclat, grain. Uniquement circuit APR / Medicube — distinct du PDRN Exosome Shot déjà au rayon.$d$,
 $d$PDRN (sodium DNA), niacinamide 5 %, hydrolyzed collagen, aqua. Liste complète sur le pot.$d$,
 $d$Soir, une noisette (capsules + gelée) sur visage. Suivre la notice officielle. Introduire un soir sur deux si sensible.$d$,
 $d$Uniquement circuit APR / Medicube officiel. Pas de PDRN gris. Patch-test 24 h. Ceci n'est pas un médicament.$d$,
 '55 g', 'Corée', 'Pot Medicube PDRN Pink Collagen Capsule Cream d''origine, hologramme et lot photographiés. Zéro marketplace gris.',
 24900, null, 8, 'SHB-MD-PCC55', '/products/medicube-pdrn-capsule.jpg?v=25',
 'normale,sèche,mixte,terne', null, true, true, true, true, 'M26-PCC', '2027-12-31'),

(192, 'anua-zero-cast-sun', 'Solaire Zero-cast SPF50+', 3, 1,
 $d$Anua Zero-cast Moisturizing Finish Sunscreen SPF50+ PA++++, 50 ml. Fini hydratant, zéro film blanc, texture fluide. Le solaire Heartleaf du quotidien à Lomé — se porte sur le toner 77 %.$d$,
 $d$UV filters, houttuynia cordata extract, hyaluronic acid, aqua. SPF50+ PA++++. Liste complète sur le tube.$d$,
 $d$Dernière étape du matin : généreux sur visage et cou. Renouveler toutes les 2 h en exposition.$d$,
 $d$Usage externe. La protection solaire ne remplace pas l'ombre. Vérifier l'indice et la DLC du lot.$d$,
 '50 ml', 'Corée', 'Tube Anua Zero-cast SPF50+ d''origine, lot photographié.',
 15900, null, 22, 'SHB-AN-ZC50', '/products/anua-zero-cast-sun.jpg?v=25',
 'sensible,normale,mixte,sèche,tous', null, true, true, true, true, 'N26-ZC50', '2028-03-31'),

(193, 'skin1004-probio-cica', 'Ampoule Probio-Cica Intensive', 9, 1,
 $d$SKIN1004 Madagascar Centella Probio-Cica Intensive Ampoule, 50 ml. Centella + ferments : barrière, rougeurs, peaux fragilisées. Texture sérum-ampoule, flacon 50 ml. Le soin « réparation » de la ligne Centella.$d$,
 $d$Centella asiatica extract, lactobacillus ferment, madecassoside, panthenol, aqua. Liste complète sur le flacon.$d$,
 $d$Soir, 3 à 4 gouttes sur peau propre, avant la crème. Peut précéder Atobarrier ou Dynasty.$d$,
 $d$Usage externe. Patch-test si barrière lésée. Ceci n'est pas un médicament.$d$,
 '50 ml', 'Corée', 'Flacon SKIN1004 Probio-Cica Intensive Ampoule d''origine, boîte, lot photographié.',
 18900, null, 14, 'SHB-S1-PC50', '/products/skin1004-probio-cica.jpg?v=25',
 'sensible,sèche,irritée,normale,mixte', null, true, true, true, true, 'S26-PC50', '2028-06-30')

on conflict (slug) do update set
  name = excluded.name,
  brand_id = excluded.brand_id,
  category_id = excluded.category_id,
  description = excluded.description,
  ingredients = excluded.ingredients,
  usage_tips = excluded.usage_tips,
  precautions = excluded.precautions,
  format_label = excluded.format_label,
  origin = excluded.origin,
  authenticity_note = excluded.authenticity_note,
  price_xof = excluded.price_xof,
  compare_at_xof = excluded.compare_at_xof,
  stock = excluded.stock,
  sku = excluded.sku,
  image_url = excluded.image_url,
  skin_types = excluded.skin_types,
  is_featured = true,
  is_new = true,
  is_active = true;

update products
set image_url = '/products/boje-dynasty-cream.jpg?v=25',
    is_new = true,
    is_featured = true
where slug = 'boje-dynasty-cream';

select setval('products_id_seq', (select max(id) from products));
