/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistanceRouteImport } from './routes/assistance'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as DomaineRouteImport } from './routes/domaine'
import { Route as EpiRouteImport } from './routes/epi'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as GuideFloozRouteImport } from './routes/guide-flooz'
import { Route as GuideMixxRouteImport } from './routes/guide-mixx'
import { Route as GuideRemiseRouteImport } from './routes/guide-remise'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarquesRouteImport } from './routes/marques'
import { Route as MobileMoneyRouteImport } from './routes/mobile-money'
import { Route as NormesCoreeRouteImport } from './routes/normes-coree'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as TendancesRouteImport } from './routes/tendances'
import { Route as AdminAchatCoreeRouteImport } from './routes/admin.achat-coree'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCommandesRouteImport } from './routes/admin.commandes'
import { Route as AdminConcurrenceRouteImport } from './routes/admin.concurrence'
import { Route as AdminEnvironnementRouteImport } from './routes/admin.environnement'
import { Route as AdminProduitsRouteImport } from './routes/admin.produits'
import { Route as AdminReglagesRouteImport } from './routes/admin.reglages'
import { Route as AdminStocksRouteImport } from './routes/admin.stocks'
import { Route as CommandesRefRouteImport } from './routes/commandes.$ref'
import { Route as MentionsCgvRouteImport } from './routes/mentions.cgv'
import { Route as MentionsConfidentialiteRouteImport } from './routes/mentions.confidentialite'
import { Route as MentionsRetoursRouteImport } from './routes/mentions.retours'
import { Route as PaiementRefRouteImport } from './routes/paiement.$ref'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as SuiviCodeRouteImport } from './routes/suivi.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaygateCallbackRouteImport } from './routes/api/paygate.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistanceRoute = AssistanceRouteImport.update({
  id: '/assistance',
  path: '/assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const DomaineRoute = DomaineRouteImport.update({
  id: '/domaine',
  path: '/domaine',
  getParentRoute: () => rootRouteImport,
} as any)
const EpiRoute = EpiRouteImport.update({
  id: '/epi',
  path: '/epi',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideFloozRoute = GuideFloozRouteImport.update({
  id: '/guide-flooz',
  path: '/guide-flooz',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideMixxRoute = GuideMixxRouteImport.update({
  id: '/guide-mixx',
  path: '/guide-mixx',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRemiseRoute = GuideRemiseRouteImport.update({
  id: '/guide-remise',
  path: '/guide-remise',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarquesRoute = MarquesRouteImport.update({
  id: '/marques',
  path: '/marques',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileMoneyRoute = MobileMoneyRouteImport.update({
  id: '/mobile-money',
  path: '/mobile-money',
  getParentRoute: () => rootRouteImport,
} as any)
const NormesCoreeRoute = NormesCoreeRouteImport.update({
  id: '/normes-coree',
  path: '/normes-coree',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const TendancesRoute = TendancesRouteImport.update({
  id: '/tendances',
  path: '/tendances',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAchatCoreeRoute = AdminAchatCoreeRouteImport.update({
  id: '/achat-coree',
  path: '/achat-coree',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConcurrenceRoute = AdminConcurrenceRouteImport.update({
  id: '/concurrence',
  path: '/concurrence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnvironnementRoute = AdminEnvironnementRouteImport.update({
  id: '/environnement',
  path: '/environnement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsRoute = AdminProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReglagesRoute = AdminReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStocksRoute = AdminStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AdminRoute,
} as any)
const CommandesRefRoute = CommandesRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => CommandesRoute,
} as any)
const MentionsCgvRoute = MentionsCgvRouteImport.update({
  id: '/mentions/cgv',
  path: '/mentions/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsConfidentialiteRoute = MentionsConfidentialiteRouteImport.update({
  id: '/mentions/confidentialite',
  path: '/mentions/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsRetoursRoute = MentionsRetoursRouteImport.update({
  id: '/mentions/retours',
  path: '/mentions/retours',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRefRoute = PaiementRefRouteImport.update({
  id: '/paiement/$ref',
  path: '/paiement/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviCodeRoute = SuiviCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SuiviRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaygateCallbackRoute = ApiPaygateCallbackRouteImport.update({
  id: '/api/paygate/callback',
  path: '/api/paygate/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistance': typeof AssistanceRoute
  '/catalogue': typeof CatalogueRoute
  '/commande': typeof CommandeRoute
  '/commandes': typeof CommandesRouteWithChildren
  '/compte': typeof CompteRoute
  '/domaine': typeof DomaineRoute
  '/epi': typeof EpiRoute
  '/favoris': typeof FavorisRoute
  '/guide-flooz': typeof GuideFloozRoute
  '/guide-mixx': typeof GuideMixxRoute
  '/guide-remise': typeof GuideRemiseRoute
  '/login': typeof LoginRoute
  '/marques': typeof MarquesRoute
  '/mobile-money': typeof MobileMoneyRoute
  '/normes-coree': typeof NormesCoreeRoute
  '/panier': typeof PanierRoute
  '/routine': typeof RoutineRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/tendances': typeof TendancesRoute
  '/admin/achat-coree': typeof AdminAchatCoreeRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/concurrence': typeof AdminConcurrenceRoute
  '/admin/environnement': typeof AdminEnvironnementRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/reglages': typeof AdminReglagesRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/commandes/$ref': typeof CommandesRefRoute
  '/mentions/cgv': typeof MentionsCgvRoute
  '/mentions/confidentialite': typeof MentionsConfidentialiteRoute
  '/mentions/retours': typeof MentionsRetoursRoute
  '/paiement/$ref': typeof PaiementRefRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/suivi/$code': typeof SuiviCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paygate/callback': typeof ApiPaygateCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistance': typeof AssistanceRoute
  '/catalogue': typeof CatalogueRoute
  '/commande': typeof CommandeRoute
  '/commandes': typeof CommandesRouteWithChildren
  '/compte': typeof CompteRoute
  '/domaine': typeof DomaineRoute
  '/epi': typeof EpiRoute
  '/favoris': typeof FavorisRoute
  '/guide-flooz': typeof GuideFloozRoute
  '/guide-mixx': typeof GuideMixxRoute
  '/guide-remise': typeof GuideRemiseRoute
  '/login': typeof LoginRoute
  '/marques': typeof MarquesRoute
  '/mobile-money': typeof MobileMoneyRoute
  '/normes-coree': typeof NormesCoreeRoute
  '/panier': typeof PanierRoute
  '/routine': typeof RoutineRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/tendances': typeof TendancesRoute
  '/admin/achat-coree': typeof AdminAchatCoreeRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/concurrence': typeof AdminConcurrenceRoute
  '/admin/environnement': typeof AdminEnvironnementRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/reglages': typeof AdminReglagesRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/commandes/$ref': typeof CommandesRefRoute
  '/mentions/cgv': typeof MentionsCgvRoute
  '/mentions/confidentialite': typeof MentionsConfidentialiteRoute
  '/mentions/retours': typeof MentionsRetoursRoute
  '/paiement/$ref': typeof PaiementRefRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/suivi/$code': typeof SuiviCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paygate/callback': typeof ApiPaygateCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistance': typeof AssistanceRoute
  '/catalogue': typeof CatalogueRoute
  '/commande': typeof CommandeRoute
  '/commandes': typeof CommandesRouteWithChildren
  '/compte': typeof CompteRoute
  '/domaine': typeof DomaineRoute
  '/epi': typeof EpiRoute
  '/favoris': typeof FavorisRoute
  '/guide-flooz': typeof GuideFloozRoute
  '/guide-mixx': typeof GuideMixxRoute
  '/guide-remise': typeof GuideRemiseRoute
  '/login': typeof LoginRoute
  '/marques': typeof MarquesRoute
  '/mobile-money': typeof MobileMoneyRoute
  '/normes-coree': typeof NormesCoreeRoute
  '/panier': typeof PanierRoute
  '/routine': typeof RoutineRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/tendances': typeof TendancesRoute
  '/admin/achat-coree': typeof AdminAchatCoreeRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/concurrence': typeof AdminConcurrenceRoute
  '/admin/environnement': typeof AdminEnvironnementRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/reglages': typeof AdminReglagesRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/commandes/$ref': typeof CommandesRefRoute
  '/mentions/cgv': typeof MentionsCgvRoute
  '/mentions/confidentialite': typeof MentionsConfidentialiteRoute
  '/mentions/retours': typeof MentionsRetoursRoute
  '/paiement/$ref': typeof PaiementRefRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/suivi/$code': typeof SuiviCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paygate/callback': typeof ApiPaygateCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistance'
    | '/catalogue'
    | '/commande'
    | '/commandes'
    | '/compte'
    | '/domaine'
    | '/epi'
    | '/favoris'
    | '/guide-flooz'
    | '/guide-mixx'
    | '/guide-remise'
    | '/login'
    | '/marques'
    | '/mobile-money'
    | '/normes-coree'
    | '/panier'
    | '/routine'
    | '/suivi'
    | '/tendances'
    | '/admin/achat-coree'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/concurrence'
    | '/admin/environnement'
    | '/admin/produits'
    | '/admin/reglages'
    | '/admin/stocks'
    | '/commandes/$ref'
    | '/mentions/cgv'
    | '/mentions/confidentialite'
    | '/mentions/retours'
    | '/paiement/$ref'
    | '/produit/$slug'
    | '/suivi/$code'
    | '/api/auth/$'
    | '/api/paygate/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistance'
    | '/catalogue'
    | '/commande'
    | '/commandes'
    | '/compte'
    | '/domaine'
    | '/epi'
    | '/favoris'
    | '/guide-flooz'
    | '/guide-mixx'
    | '/guide-remise'
    | '/login'
    | '/marques'
    | '/mobile-money'
    | '/normes-coree'
    | '/panier'
    | '/routine'
    | '/suivi'
    | '/tendances'
    | '/admin/achat-coree'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/concurrence'
    | '/admin/environnement'
    | '/admin/produits'
    | '/admin/reglages'
    | '/admin/stocks'
    | '/commandes/$ref'
    | '/mentions/cgv'
    | '/mentions/confidentialite'
    | '/mentions/retours'
    | '/paiement/$ref'
    | '/produit/$slug'
    | '/suivi/$code'
    | '/api/auth/$'
    | '/api/paygate/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistance'
    | '/catalogue'
    | '/commande'
    | '/commandes'
    | '/compte'
    | '/domaine'
    | '/epi'
    | '/favoris'
    | '/guide-flooz'
    | '/guide-mixx'
    | '/guide-remise'
    | '/login'
    | '/marques'
    | '/mobile-money'
    | '/normes-coree'
    | '/panier'
    | '/routine'
    | '/suivi'
    | '/tendances'
    | '/admin/achat-coree'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/concurrence'
    | '/admin/environnement'
    | '/admin/produits'
    | '/admin/reglages'
    | '/admin/stocks'
    | '/commandes/$ref'
    | '/mentions/cgv'
    | '/mentions/confidentialite'
    | '/mentions/retours'
    | '/paiement/$ref'
    | '/produit/$slug'
    | '/suivi/$code'
    | '/api/auth/$'
    | '/api/paygate/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistanceRoute: typeof AssistanceRoute
  CatalogueRoute: typeof CatalogueRoute
  CommandeRoute: typeof CommandeRoute
  CommandesRoute: typeof CommandesRouteWithChildren
  CompteRoute: typeof CompteRoute
  DomaineRoute: typeof DomaineRoute
  EpiRoute: typeof EpiRoute
  FavorisRoute: typeof FavorisRoute
  GuideFloozRoute: typeof GuideFloozRoute
  GuideMixxRoute: typeof GuideMixxRoute
  GuideRemiseRoute: typeof GuideRemiseRoute
  LoginRoute: typeof LoginRoute
  MarquesRoute: typeof MarquesRoute
  MobileMoneyRoute: typeof MobileMoneyRoute
  NormesCoreeRoute: typeof NormesCoreeRoute
  PanierRoute: typeof PanierRoute
  RoutineRoute: typeof RoutineRoute
  SuiviRoute: typeof SuiviRouteWithChildren
  TendancesRoute: typeof TendancesRoute
  MentionsCgvRoute: typeof MentionsCgvRoute
  MentionsConfidentialiteRoute: typeof MentionsConfidentialiteRoute
  MentionsRetoursRoute: typeof MentionsRetoursRoute
  PaiementRefRoute: typeof PaiementRefRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaygateCallbackRoute: typeof ApiPaygateCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistance': {
      id: '/assistance'
      path: '/assistance'
      fullPath: '/assistance'
      preLoaderRoute: typeof AssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domaine': {
      id: '/domaine'
      path: '/domaine'
      fullPath: '/domaine'
      preLoaderRoute: typeof DomaineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epi': {
      id: '/epi'
      path: '/epi'
      fullPath: '/epi'
      preLoaderRoute: typeof EpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-flooz': {
      id: '/guide-flooz'
      path: '/guide-flooz'
      fullPath: '/guide-flooz'
      preLoaderRoute: typeof GuideFloozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-mixx': {
      id: '/guide-mixx'
      path: '/guide-mixx'
      fullPath: '/guide-mixx'
      preLoaderRoute: typeof GuideMixxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-remise': {
      id: '/guide-remise'
      path: '/guide-remise'
      fullPath: '/guide-remise'
      preLoaderRoute: typeof GuideRemiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marques': {
      id: '/marques'
      path: '/marques'
      fullPath: '/marques'
      preLoaderRoute: typeof MarquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-money': {
      id: '/mobile-money'
      path: '/mobile-money'
      fullPath: '/mobile-money'
      preLoaderRoute: typeof MobileMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normes-coree': {
      id: '/normes-coree'
      path: '/normes-coree'
      fullPath: '/normes-coree'
      preLoaderRoute: typeof NormesCoreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendances': {
      id: '/tendances'
      path: '/tendances'
      fullPath: '/tendances'
      preLoaderRoute: typeof TendancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/achat-coree': {
      id: '/admin/achat-coree'
      path: '/achat-coree'
      fullPath: '/admin/achat-coree'
      preLoaderRoute: typeof AdminAchatCoreeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/concurrence': {
      id: '/admin/concurrence'
      path: '/concurrence'
      fullPath: '/admin/concurrence'
      preLoaderRoute: typeof AdminConcurrenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/environnement': {
      id: '/admin/environnement'
      path: '/environnement'
      fullPath: '/admin/environnement'
      preLoaderRoute: typeof AdminEnvironnementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits': {
      id: '/admin/produits'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminProduitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reglages': {
      id: '/admin/reglages'
      path: '/reglages'
      fullPath: '/admin/reglages'
      preLoaderRoute: typeof AdminReglagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stocks': {
      id: '/admin/stocks'
      path: '/stocks'
      fullPath: '/admin/stocks'
      preLoaderRoute: typeof AdminStocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/commandes/$ref': {
      id: '/commandes/$ref'
      path: '/$ref'
      fullPath: '/commandes/$ref'
      preLoaderRoute: typeof CommandesRefRouteImport
      parentRoute: typeof CommandesRoute
    }
    '/mentions/cgv': {
      id: '/mentions/cgv'
      path: '/mentions/cgv'
      fullPath: '/mentions/cgv'
      preLoaderRoute: typeof MentionsCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions/confidentialite': {
      id: '/mentions/confidentialite'
      path: '/mentions/confidentialite'
      fullPath: '/mentions/confidentialite'
      preLoaderRoute: typeof MentionsConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions/retours': {
      id: '/mentions/retours'
      path: '/mentions/retours'
      fullPath: '/mentions/retours'
      preLoaderRoute: typeof MentionsRetoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/$ref': {
      id: '/paiement/$ref'
      path: '/paiement/$ref'
      fullPath: '/paiement/$ref'
      preLoaderRoute: typeof PaiementRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/$code': {
      id: '/suivi/$code'
      path: '/$code'
      fullPath: '/suivi/$code'
      preLoaderRoute: typeof SuiviCodeRouteImport
      parentRoute: typeof SuiviRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paygate/callback': {
      id: '/api/paygate/callback'
      path: '/api/paygate/callback'
      fullPath: '/api/paygate/callback'
      preLoaderRoute: typeof ApiPaygateCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAchatCoreeRoute: typeof AdminAchatCoreeRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminConcurrenceRoute: typeof AdminConcurrenceRoute
  AdminEnvironnementRoute: typeof AdminEnvironnementRoute
  AdminProduitsRoute: typeof AdminProduitsRoute
  AdminReglagesRoute: typeof AdminReglagesRoute
  AdminStocksRoute: typeof AdminStocksRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAchatCoreeRoute: AdminAchatCoreeRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminConcurrenceRoute: AdminConcurrenceRoute,
  AdminEnvironnementRoute: AdminEnvironnementRoute,
  AdminProduitsRoute: AdminProduitsRoute,
  AdminReglagesRoute: AdminReglagesRoute,
  AdminStocksRoute: AdminStocksRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CommandesRouteChildren {
  CommandesRefRoute: typeof CommandesRefRoute
}

const CommandesRouteChildren: CommandesRouteChildren = {
  CommandesRefRoute: CommandesRefRoute,
}

const CommandesRouteWithChildren = CommandesRoute._addFileChildren(
  CommandesRouteChildren,
)

interface SuiviRouteChildren {
  SuiviCodeRoute: typeof SuiviCodeRoute
}

const SuiviRouteChildren: SuiviRouteChildren = {
  SuiviCodeRoute: SuiviCodeRoute,
}

const SuiviRouteWithChildren = SuiviRoute._addFileChildren(SuiviRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistanceRoute: AssistanceRoute,
  CatalogueRoute: CatalogueRoute,
  CommandeRoute: CommandeRoute,
  CommandesRoute: CommandesRouteWithChildren,
  CompteRoute: CompteRoute,
  DomaineRoute: DomaineRoute,
  EpiRoute: EpiRoute,
  FavorisRoute: FavorisRoute,
  GuideFloozRoute: GuideFloozRoute,
  GuideMixxRoute: GuideMixxRoute,
  GuideRemiseRoute: GuideRemiseRoute,
  LoginRoute: LoginRoute,
  MarquesRoute: MarquesRoute,
  MobileMoneyRoute: MobileMoneyRoute,
  NormesCoreeRoute: NormesCoreeRoute,
  PanierRoute: PanierRoute,
  RoutineRoute: RoutineRoute,
  SuiviRoute: SuiviRouteWithChildren,
  TendancesRoute: TendancesRoute,
  MentionsCgvRoute: MentionsCgvRoute,
  MentionsConfidentialiteRoute: MentionsConfidentialiteRoute,
  MentionsRetoursRoute: MentionsRetoursRoute,
  PaiementRefRoute: PaiementRefRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaygateCallbackRoute: ApiPaygateCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
